package org.campagnelab.metar.inspect.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.campagnelab.metar.tables.generationhelpers.RPath;
import jetbrains.mps.util.MacrosFactory;
import java.io.File;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_8016431400514006106(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "tableName");
  }

  public static Object propertyMacro_GetPropertyValue_8016431400514009759(final PropertyMacroContext _context) {
    return RPath.escape(MacrosFactory.getGlobal().expandPath("${org.campagnelab.metaR.results_dir}") + File.separator + "table_" + SPropertyOperations.getString(_context.getNode(), "tableName") + "_" + Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "tableId")) + ".tsv");
  }

  public static Object propertyMacro_GetPropertyValue_962445451564175837(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }
}
