package org.campagnelab.metar.tables.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ColumnRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ColumnRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.tables.structure.ColumnRef";
  }
}
