package org.campagnelab.metar.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class ColumnGroup_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Iterable<SNode> call_uses_8031339867721231487(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "usesRefs", true)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "usage", false);
      }
    });
  }
}
