package org.campagnelab.metar.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;

public class ColumnGroupContainer_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode call_getContainer_3402264987266367839(SAbstractConcept thisConcept, SModel model) {
    SNode container = ListSequence.fromList(SModelOperations.getRootsIncludingImported(model, "org.campagnelab.metar.tables.structure.ColumnGroupContainer")).first();
    if (container != null) {
      return container;
    }
    container = SModelOperations.createNewRootNode(model, "org.campagnelab.metar.tables.structure.ColumnGroupContainer", null);
    return container;
  }
}
