package org.campagnelab.metar.tables.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ColumnGroupContainer_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ColumnGroupContainer_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.tables.structure.ColumnGroupContainer";
  }
}
