package org.campagnelab.metar.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ImportTable_Behavior {
  public static void init(SNode thisNode) {
  }
}
