package org.campagnelab.metar.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.io.File;
import jetbrains.mps.util.MacrosFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class Plot_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "width", "" + (200));
    SPropertyOperations.set(thisNode, "height", "" + (200));
  }

  public static String call_getPath_8016431400518331231(SNode thisNode) {
    return new File(MacrosFactory.getGlobal().expandPath("${org.campagnelab.hta.results_dir}/plot_" + SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(thisNode), "org.campagnelab.metar.tables.structure.Statement"), "id") + "_" + (SPropertyOperations.getInteger(thisNode, "id")) + ".png")).getAbsolutePath();
  }

  public static String call_getStatementId_8013388156563811997(SNode thisNode) {
    return SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(thisNode), "org.campagnelab.metar.tables.structure.Statement"), "id");
  }

  public static String call_getTableName_8013388156564326838(SNode thisNode) {
    String tableName = BehaviorReflection.invokeVirtual(String.class, SNodeOperations.cast(SNodeOperations.getParent(thisNode), "org.campagnelab.metar.tables.structure.PlotBuilderStatement"), "virtual_getTableName_8013388156564360086", new Object[]{});
    return tableName;
  }
}
