#!/bin/bash

#installation script for MetaR 1.3.2 (works with MPS3.2.x on MacOS and Linux)
# 
# plugins installed by the script:
#  MetaR 1.3.2
#  TextOutput 1.3.0
#  XChart 1.1.10
#  UI 1.0.3
#  Logger 1.0.2

function detectTargetDir() {

 case "$(uname -s)" in

   Darwin)
     echo 'Mac OS X platform detected.'
     TARGET_INSTALLATION_DIR="${HOME}/Library/Application Support/MPS32"
     ;;

   Linux)
     echo 'Linux platform detected.'
     TARGET_INSTALLATION_DIR="${HOME}/.MPS31/config/plugins/"
    ;;

   CYGWIN*)
     echo 'MS Windows platform with CYGWIN detected.'
     TARGET_INSTALLATION_DIR="${USERPROFILE}/.MPS32/config/plugins/"
     ;;

   MINGW32*|MSYS*|Windows*)
     echo 'MS Windows platform detected.'
     echo "This installer does not work on a Windows machine."
     cleanup
     exit 1
     ;;

   *)
     echo 'No platform detected, assuming Mac OS X.'
     TARGET_INSTALLATION_DIR="${HOME}/Library/Application Support/MPS32" 
     ;;
 esac

}

function cleanup() {
	echo "Removing installation files..."
	rm -rf "${WORKING_DIR}/download"
	echo "done"	
}

function download() {
	echo "Downloading $2..."
	curl -fsSLJ -o download/$2 $1; status=$?
	if [ $status -ne 0 ]; then
        	echo "Error: MetaR installer cannot download a required file ($2) -- make sure you can connect the internet"
		cleanup
		exit 1
	fi
	
}


WORKING_DIR=`pwd`
rm -rf "${WORKING_DIR}/download"
mkdir "${WORKING_DIR}/download"
download "http://campagnelab.org/?wpdmact=process&did=MTI0LmhvdGxpbms" metaR.zip
download "http://campagnelab.org/?wpdmact=process&did=MTIxLmhvdGxpbms" XChart.zip
download "http://campagnelab.org/?wpdmact=process&did=MTI1LmhvdGxpbms" TextOutput.zip
download "http://campagnelab.org/?wpdmact=process&did=MTE5LmhvdGxpbms" UI.zip 
download "http://campagnelab.org/?wpdmact=process&did=MTIwLmhvdGxpbms" Logger.zip

detectTargetDir
mkdir -p "${TARGET_INSTALLATION_DIR}"

for plugin_file in `ls ${WORKING_DIR}/download/*.zip`; do
	echo "Installing ${filename}"
	cp "$plugin_file" "${TARGET_INSTALLATION_DIR}"
	filename=`basename $plugin_file`
	cd "${TARGET_INSTALLATION_DIR}"
	rm -rf "${TARGET_INSTALLATION_DIR}/${filename%.zip}"
	unzip "${filename}"
	rm "${filename}"
	cd "${WORKING_DIR}"
	echo "${plugin_file} installed."
done
cleanup
echo "MetaR has been successfully installed."
