package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AbstractRowFilter_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements RowFilter_BehaviorDescriptor {
  public AbstractRowFilter_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.AbstractRowFilter";
  }
}
