package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ColumnAnnotation_Behavior {
  public static void init(SNode thisNode) {
  }
}
