package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */


public class EmptyLine_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public EmptyLine_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.EmptyLine";
  }
}
