package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import org.campagnelab.hta.script.behavior.Statement_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class Heatmap_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public Heatmap_BehaviorDescriptor() {
  }

  public Iterable<String> virtual_dependencies_6853668812000956111(SNode thisNode) {
    return Heatmap_Behavior.virtual_dependencies_6853668812000956111(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.Heatmap";
  }
}
