package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class JoinTables_BehaviorDescriptor extends TableTransformation_BehaviorDescriptor {
  public JoinTables_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_dependencies_7074867102589853662(SNode thisNode) {
    return JoinTables_Behavior.virtual_dependencies_7074867102589853662(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.JoinTables";
  }
}
