package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class PlotBuilderStatement_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getTableName_8013388156564360086(SNode thisNode) {
    return "null";
  }

  @Deprecated
  public static String call_getTableName_8013388156564360086(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_getTableName_8013388156564360086", new Object[]{});
  }

  @Deprecated
  public static String callSuper_getTableName_8013388156564360086(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "org.campagnelab.hta.tables.structure.PlotBuilderStatement"), callerConceptFqName, "virtual_getTableName_8013388156564360086", new Class[]{SNode.class}, new Object[]{});
  }
}
