package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */


public class PredictWithModel_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public PredictWithModel_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.PredictWithModel";
  }
}
