package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Range_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Range_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.Range";
  }
}
