package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */


public class ScatterPlotStyle_BehaviorDescriptor extends PlotStyle_BehaviorDescriptor {
  public ScatterPlotStyle_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.ScatterPlotStyle";
  }
}
