package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Statement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Statement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.Statement";
  }
}
