package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;

public class StatementList_BehaviorDescriptor extends Statement_BehaviorDescriptor implements ScopeProvider_BehaviorDescriptor {
  public StatementList_BehaviorDescriptor() {
  }

  public Iterable<String> virtual_dependencies_8962032619593737608(SNode thisNode) {
    return StatementList_Behavior.virtual_dependencies_8962032619593737608(thisNode);
  }

  public Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    return StatementList_Behavior.virtual_getScope_3734116213129936182(thisNode, kind, child);
  }

  public Scope virtual_getScope_7722139651431880752(SNode thisNode, SNode kind, String role, int index) {
    return StatementList_Behavior.virtual_getScope_7722139651431880752(thisNode, kind, role, index);
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.StatementList";
  }
}
