package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.scope.CompositeScope;
import jetbrains.mps.lang.scopes.runtime.ScopeUtils;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class StatementList_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {

    if (kind == SConceptOperations.findConceptDeclaration("org.campagnelab.hta.tables.structure.FutureTable")) {
      List<SNode> descendants = SNodeOperations.getDescendants(thisNode, null, false, new String[]{});
      final int myIndex = descendants.indexOf(child);
      Iterable<SNode> before = ListSequence.fromList(descendants).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SNodeOperations.getIndexInParent(it) < myIndex && SNodeOperations.isInstanceOf(it, "org.campagnelab.hta.tables.structure.FutureTable");
        }
      });
      return CompositeScope.createComposite(ScopeUtils.lazyParentScope(thisNode, kind), ListScope.forNamedElements(before));
    }
    return ScopeUtils.lazyParentScope(thisNode, kind);
  }

  public static Scope virtual_getScope_7722139651431880752(SNode thisNode, SNode kind, String role, int index) {
    return BehaviorReflection.invokeSuper(Scope.class, thisNode, "jetbrains.mps.lang.core.structure.ScopeProvider", "virtual_getScope_7722139651431880752", new Object[]{kind, role, index});
  }
}
