package org.campagnelab.hta.tables.behavior;

/*Generated by MPS */


public class TrainLinearModel_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public TrainLinearModel_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.tables.structure.TrainLinearModel";
  }
}
