package org.campagnelab.metar.tables.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.metar.tables.generationhelpers.NameHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.campagnelab.metar.tables.behavior.Table_Behavior;
import jetbrains.mps.internal.collections.runtime.IterableUtils;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import java.util.Set;
import org.campagnelab.metar.tables.behavior.FutureTable_Behavior;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.campagnelab.metar.tables.behavior.ColumnGroup_Behavior;
import org.campagnelab.metar.tables.behavior.Heatmap_Behavior;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.campagnelab.metar.tables.behavior.Plot_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import org.campagnelab.metar.tables.behavior.Multiplot_Behavior;
import org.campagnelab.metar.tables.behavior.Render_Behavior;
import org.campagnelab.metar.tables.behavior.ColumnRef_Behavior;
import org.campagnelab.metar.tables.behavior.Model_Behavior;
import jetbrains.mps.util.MacrosFactory;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.TemplateQueryContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import org.campagnelab.metar.tables.behavior.TableRef_Behavior;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.generator.template.MappingScriptContext;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static boolean baseMappingRule_Condition_4166618652718994624(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "rowFilter", true), "org.campagnelab.metar.tables.structure.FilterWithIDList");
  }

  public static boolean baseMappingRule_Condition_7783277237109298882(final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "rowFilter", true), "org.campagnelab.metar.tables.structure.FilterWithExpression");
  }

  public static boolean baseMappingRule_Condition_4067230457182112179(final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commentedStatement", true)).all(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.TextCommentPart");
      }
    });
  }

  public static boolean baseMappingRule_Condition_4067230457182454052(final BaseMappingRuleContext _context) {
    return !(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "commentedStatement", true)).all(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SNodeOperations.isInstanceOf(it, "jetbrains.mps.baseLanguage.structure.TextCommentPart");
      }
    }));
  }

  public static Object propertyMacro_GetPropertyValue_8459500803717501074(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_8459500803717509382(final PropertyMacroContext _context) {
    return Table_Behavior.call_resolvePath_578023650347534658(SLinkOperations.getTarget(_context.getNode(), "table", false));
  }

  public static Object propertyMacro_GetPropertyValue_3377220465482237537(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(Table_Behavior.call_getRColumnTypes_3377220465482555543(SLinkOperations.getTarget(_context.getNode(), "table", false))).select(new ISelector<String, String>() {
      public String select(String rType) {
        return "\"" + rType + "\"";
      }
    }), ", ");
  }

  public static Object propertyMacro_GetPropertyValue_962445451564484796(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_1549006859294737198(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_2826789978070559645(final PropertyMacroContext _context) {
    return IterableUtils.join(SetSequence.fromSet(BehaviorReflection.invokeVirtual((Class<Set<String>>) ((Class) Object.class), SLinkOperations.getTarget(SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.metar.tables.structure.JoinTables", false, false), "byKeySelection", true), "virtual_getColumnNames_8016431400515512083", new Object[]{SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", false), "table", false), "columns", true)})), "\",\"");
  }

  public static Object propertyMacro_GetPropertyValue_2826789978070879122(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "outputTable", true), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_3377220465483753723(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "inputTables", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, "table", false) != null);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "table", false);
      }
    }).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return NameHelper.RName(SPropertyOperations.getString(it, "name"));
      }
    }), ", ");
  }

  public static Object propertyMacro_GetPropertyValue_962445451565867504(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_8016431400513898053(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "outputTable", true), "id");
  }

  public static Object propertyMacro_GetPropertyValue_8016431400514098092(final PropertyMacroContext _context) {
    return FutureTable_Behavior.call_getCleanTableName_4166618652720345586(SLinkOperations.getTarget(_context.getNode(), "outputTable", true));
  }

  public static Object propertyMacro_GetPropertyValue_5703306641526023067(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_8016431400516940527(final PropertyMacroContext _context) {
    // Generate the c(),c() expressions 
    List<String> columnNames = ListSequence.fromList(new ArrayList<String>());
    String c1 = "c(";
    String c2 = "c(";
    ListSequence.fromList(columnNames).addSequence(SetSequence.fromSet(BehaviorReflection.invokeVirtual((Class<Set<String>>) ((Class) Object.class), SLinkOperations.getTarget(_context.getNode(), "dataSelection", true), "virtual_getColumnNames_8016431400515512083", new Object[]{SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)})));

    IterableUtils.join(SetSequence.fromSet(BehaviorReflection.invokeVirtual((Class<Set<String>>) ((Class) Object.class), SLinkOperations.getTarget(_context.getNode(), "dataSelection", true), "virtual_getColumnNames_8016431400515512083", new Object[]{SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)})).select(new ISelector<String, String>() {
      public String select(String it) {
        return "\"" + it + "\"";
      }
    }), ",");
    int index = 0;
    for (final String columnName : columnNames) {
      String group = SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getTargets(AttributeOperations.getAttribute(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)).findFirst(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return SPropertyOperations.getString(it, "name").equals(columnName);
        }
      }), new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation")), "groups", true)).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return Sequence.fromIterable(ColumnGroup_Behavior.call_uses_8031339867721231487(SLinkOperations.getTarget(it, "columnGroup", false))).any(new IWhereFilter<SNode>() {
            public boolean accept(SNode use) {
              return eq_x583g4_a0a0a0a0a0a0a0a0a0a0a0a0a8a71(SPropertyOperations.getString(use, "name"), "heatmap");
            }
          });
        }
      }).where(new IWhereFilter<SNode>() {
        public boolean accept(SNode it) {
          return (SLinkOperations.getTarget(it, "columnGroup", false) != null);
        }
      }).select(new ISelector<SNode, SNode>() {
        public SNode select(SNode it) {
          return SLinkOperations.getTarget(it, "columnGroup", false);
        }
      }).first(), "name");
      c1 += "\"" + group + "\"";
      c2 += "\"" + columnName + "\"";
      index += 1;
      if (index != ListSequence.fromList(columnNames).count()) {
        c1 += ",";
        c2 += ",";
      }
    }
    c1 += "), ";
    c2 += ")";
    return c1 + c2;
  }

  public static Object propertyMacro_GetPropertyValue_6583618001725029807(final PropertyMacroContext _context) {
    return IterableUtils.join(Sequence.fromIterable(Heatmap_Behavior.call_selectedColumnNames_5703306641535871171(_context.getNode())).select(new ISelector<String, String>() {
      public String select(String it) {
        return "\"" + it + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_8016431400515494040(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_5703306641531063834(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5703306641529451500(final PropertyMacroContext _context) {
    // calculate the column group names for a set of usages, in the same order as sample names: 
    final List<String> colGroups = ListSequence.fromList(new ArrayList<String>());
    final SNode heatmap = ((SNode) _context.getVariable("var:heatmap"));
    if (LOG.isInfoEnabled()) {
      LOG.info("heatmap:" + heatmap);
    }
    Sequence.fromIterable(Heatmap_Behavior.call_selectedColumnNames_5703306641535871171(heatmap)).visitAll(new IVisitor<String>() {
      public void visit(final String sampleName) {
        if (LOG.isInfoEnabled()) {
          LOG.info("sampleName:" + sampleName);
        }
        ListSequence.fromList(colGroups).addElement(SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getTargets(AttributeOperations.getAttribute(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(heatmap, "table", true), "table", false), "columns", true)).findFirst(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return eq_x583g4_a0a0a0a0a0a0a0a0a0a1a0a0a0a4a12(SPropertyOperations.getString(it, "name"), sampleName);
          }
        }), new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation")), "groups", true)).where(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return (SLinkOperations.getTarget(it, "columnGroup", false) != null);
          }
        }).select(new ISelector<SNode, SNode>() {
          public SNode select(SNode it) {
            return SLinkOperations.getTarget(it, "columnGroup", false);
          }
        }).findFirst(new IWhereFilter<SNode>() {
          public boolean accept(SNode group) {
            return ListSequence.fromList(SLinkOperations.getTargets(group, "usesRefs", true)).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return (SLinkOperations.getTarget(it, "usage", false) != null);
              }
            }).select(new ISelector<SNode, SNode>() {
              public SNode select(SNode it) {
                return SLinkOperations.getTarget(it, "usage", false);
              }
            }).any(new IWhereFilter<SNode>() {
              public boolean accept(SNode usage) {
                return eq_x583g4_a0a0a0a0a0a0a0a0a0a0a1a0a0a0a4a12(SPropertyOperations.getString(usage, "name"), SPropertyOperations.getString(_context.getNode(), "name"));
              }
            });
          }
        }), "name"));
      }
    });
    return IterableUtils.join(ListSequence.fromList(colGroups).select(new ISelector<String, String>() {
      public String select(String name) {
        return "\"" + name + "\"";
      }
    }), ",");
    // <node> 
  }

  public static Object propertyMacro_GetPropertyValue_5703306641531276227(final PropertyMacroContext _context) {
    return IterableUtils.join(SetSequence.fromSet(BehaviorReflection.invokeVirtual((Class<Set<String>>) ((Class) Object.class), SLinkOperations.getTarget(_context.getNode(), "dataSelection", true), "virtual_getColumnNames_8016431400515512083", new Object[]{SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)})).select(new ISelector<String, String>() {
      public String select(String col) {
        return "\"" + col + "\"";
      }
    }), ", ");
  }

  public static Object propertyMacro_GetPropertyValue_8016431400519661974(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_8709280678589047369(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return ListSequence.fromList(SLinkOperations.getTargets(AttributeOperations.getAttribute(it, new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation")), "groups", true)).any(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return eq_x583g4_a0a0a0a0a0a0a0a0a0a0a42(SPropertyOperations.getString(SLinkOperations.getTarget(it, "columnGroup", false), "name"), "ID");
          }
        });
      }
    }), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6583618001731952994(final PropertyMacroContext _context) {
    return Boolean.toString(((SLinkOperations.getTarget(_context.getNode(), "annotations", true) != null) ? SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "annotations", true), "clusterRows") : false)).toUpperCase();
  }

  public static Object propertyMacro_GetPropertyValue_6583618001731925657(final PropertyMacroContext _context) {
    return Boolean.toString(((SLinkOperations.getTarget(_context.getNode(), "annotations", true) != null) ? SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "annotations", true), "clusterColumns") : false)).toUpperCase();
  }

  public static Object propertyMacro_GetPropertyValue_8016431400518316174(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getPath_8016431400518331231(SLinkOperations.getTarget(_context.getNode(), "plot", true));
  }

  public static Object propertyMacro_GetPropertyValue_6583618001716976677(final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "annotations", true) != null) && SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "annotations", true), "scaling", true)), "org.campagnelab.metar.tables.structure.ScaleByRow")) {
      return "row";
    }
    if ((SLinkOperations.getTarget(_context.getNode(), "annotations", true) != null) && SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "annotations", true), "scaling", true)), "org.campagnelab.metar.tables.structure.ScaleByColumn")) {
      return "column";
    }
    return "none";
  }

  public static Object propertyMacro_GetPropertyValue_5703306641526063165(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getPath_8016431400518331231(SLinkOperations.getTarget(_context.getNode(), "plot", true));
  }

  public static Object propertyMacro_GetPropertyValue_5703306641526063176(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "plot", true), "width"));
  }

  public static Object propertyMacro_GetPropertyValue_5703306641526063188(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "plot", true), "height"));
  }

  public static Object propertyMacro_GetPropertyValue_5703306641526099747(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_5703306641526099756(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_962445451565905959(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_4166618652718861915(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "destination", true), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_4166618652718881188(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_4166618652718897455(final PropertyMacroContext _context) {
    // need the name of the column with the ID group in the source table 
    return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode col) {
        return ListSequence.fromList(SLinkOperations.getTargets(AttributeOperations.getAttribute(col, new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation")), "groups", true)).any(new IWhereFilter<SNode>() {
          public boolean accept(SNode g) {
            return eq_x583g4_a0a0a0a0a0a0a0a0a0a1a73("ID", SPropertyOperations.getString(SLinkOperations.getTarget(g, "columnGroup", false), "name"));
          }
        });
      }
    }), "name");
  }

  public static Object propertyMacro_GetPropertyValue_4166618652718988151(final PropertyMacroContext _context) {
    // need the list of row names built by the RowFilter strategy 
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "rowFilter", true), "org.campagnelab.metar.tables.structure.FilterWithIDList"), "set", false), "ids", true)).select(new ISelector<SNode, String>() {
      public String select(SNode id) {
        return "\"" + SPropertyOperations.getString(id, "id") + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_4166618652720481126(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "destination", true), "id");
  }

  public static Object propertyMacro_GetPropertyValue_4166618652720481135(final PropertyMacroContext _context) {
    return FutureTable_Behavior.call_getCleanTableName_4166618652720345586(SLinkOperations.getTarget(_context.getNode(), "destination", true));
  }

  public static Object propertyMacro_GetPropertyValue_962445451565883665(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_7783277237109312574(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "destination", true), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_7783277237109312586(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_7783277237109312679(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "destination", true), "id");
  }

  public static Object propertyMacro_GetPropertyValue_7783277237109312688(final PropertyMacroContext _context) {
    return FutureTable_Behavior.call_getCleanTableName_4166618652720345586(SLinkOperations.getTarget(_context.getNode(), "destination", true));
  }

  public static Object propertyMacro_GetPropertyValue_7783277237109312700(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_3687343996977891854(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_6001041468486989837(final PropertyMacroContext _context) {
    return "\"" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "x", true), "col", false), "name") + "\",\"" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "y", true), "col", false), "name") + "\"" + (((SLinkOperations.getTarget(_context.getNode(), "groupBy", true) != null) ? "\"" + SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "groupBy", true), "col", false), "name") + "\"" : ""));
  }

  public static Object propertyMacro_GetPropertyValue_6001041468487574285(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_6001041468487040669(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6001041468487047756(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "x", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3442436599519388467(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "x", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3442436599519389386(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8286430004408149347(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "xRange", true), "min");
  }

  public static Object propertyMacro_GetPropertyValue_8286430004408162182(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "xRange", true), "max");
  }

  public static Object propertyMacro_GetPropertyValue_8286430004408178285(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "yRange", true), "min");
  }

  public static Object propertyMacro_GetPropertyValue_8286430004408178299(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "yRange", true), "max");
  }

  public static Object propertyMacro_GetPropertyValue_3442436599519391775(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "groupBy", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3442436599519473717(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", false), "xLabel");
  }

  public static Object propertyMacro_GetPropertyValue_3442436599519485503(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", false), "yLabel");
  }

  public static Object propertyMacro_GetPropertyValue_5333555603574514247(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", false), "title");
  }

  public static Object propertyMacro_GetPropertyValue_6001041468487057584(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "x", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_4842667988068041245(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "xRange", true), "min");
  }

  public static Object propertyMacro_GetPropertyValue_4842667988068041258(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "xRange", true), "max");
  }

  public static Object propertyMacro_GetPropertyValue_4842667988068043231(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "yRange", true), "min");
  }

  public static Object propertyMacro_GetPropertyValue_4842667988068043244(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "yRange", true), "max");
  }

  public static Object propertyMacro_GetPropertyValue_6001041468487052823(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5333555603574492550(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", false), "xLabel");
  }

  public static Object propertyMacro_GetPropertyValue_5333555603574505248(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", false), "yLabel");
  }

  public static Object propertyMacro_GetPropertyValue_6001041468488153342(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getPath_8016431400518331231(SLinkOperations.getTarget(_context.getNode(), "plot", true));
  }

  public static Object propertyMacro_GetPropertyValue_8962032619586874007(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "plot", true), "width"));
  }

  public static Object propertyMacro_GetPropertyValue_8962032619586885769(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "plot", true), "height"));
  }

  public static Object propertyMacro_GetPropertyValue_3687343996977896525(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_3687343996977814405(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_8013388156564094629(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_3687343996977485903(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "numRows"));
  }

  public static Object propertyMacro_GetPropertyValue_3687343996977498069(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "numColumns"));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988069520977(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "numColumns") * SPropertyOperations.getInteger(_context.getNode(), "numRows"));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988069572975(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "numRows"));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988069575658(final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "numColumns"));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988069640645(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(Multiplot_Behavior.call_getMaxWidths_4842667988070020633(_context.getNode())).select(new ISelector<Double, String>() {
      public String select(Double it) {
        return Double.toString(it);
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_4842667988069643418(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(Multiplot_Behavior.call_getMaxHeights_4842667988070188543(_context.getNode())).select(new ISelector<Double, String>() {
      public String select(Double it) {
        return Double.toString(it);
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_3687343996977968654(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getStatementId_8013388156563811997(SLinkOperations.getTarget(_context.getNode(), "plot", false));
  }

  public static Object propertyMacro_GetPropertyValue_3687343996978017155(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getTableName_8013388156564326838(SLinkOperations.getTarget(_context.getNode(), "plot", false));
    // <node> 
  }

  public static Object propertyMacro_GetPropertyValue_8962032619585609533(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getPath_8016431400518331231(SLinkOperations.getTarget(_context.getNode(), "destination", true));
  }

  public static Object propertyMacro_GetPropertyValue_2517666855465633575(final PropertyMacroContext _context) {
    return Double.toString(BehaviorReflection.invokeVirtual(Double.TYPE, _context.getNode(), "virtual_estimateWidth_4842667988071989466", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_8962032619588507046(final PropertyMacroContext _context) {
    return Double.toString(BehaviorReflection.invokeVirtual(Double.TYPE, _context.getNode(), "virtual_estimateHeight_4842667988071995771", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_8013388156564134449(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_8013388156564208057(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getTableName_8013388156564360086", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4842667988067748143(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_3402264987267838443(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6583618001733640982(final PropertyMacroContext _context) {
    return IterableUtils.join(Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<String>>) ((Class) Object.class), _context.getNode(), "virtual_bioConductorDependencies_6583618001733614174", new Object[]{})).select(new ISelector<String, String>() {
      public String select(String it) {
        return "\"" + it + "\"";
      }
    }), ", ");
  }

  public static Object propertyMacro_GetPropertyValue_6853668812000652063(final PropertyMacroContext _context) {
    return IterableUtils.join(Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<String>>) ((Class) Object.class), _context.getNode(), "virtual_dependencies_8962032619593737482", new Object[]{})).select(new ISelector<String, String>() {
      public String select(String it) {
        return "if (!require(\"" + it + "\")) {install.packages(\"" + it + "\",repos='http://cran.us.r-project.org'); library(\"" + it + "\")}";
      }
    }), "\n");
  }

  public static Object propertyMacro_GetPropertyValue_1488175004227207860(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "_script";
  }

  public static Object propertyMacro_GetPropertyValue_8013388156563793440(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getStatementId_8013388156563811997(SLinkOperations.getTarget(_context.getNode(), "plot", false));
  }

  public static Object propertyMacro_GetPropertyValue_8013388156564384949(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getTableName_8013388156564326838(SLinkOperations.getTarget(_context.getNode(), "plot", false));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988067759226(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_4842667988071959723(final PropertyMacroContext _context) {
    return Render_Behavior.call_getDestinationPath_4842667988071587758(SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.metar.tables.structure.Render", false, false));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988071972393(final PropertyMacroContext _context) {
    SNode render = SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.metar.tables.structure.Render", false, false);
    if (isNotEmptyString(SPropertyOperations.getString(render, "width"))) {
      return SPropertyOperations.getString(render, "width");
    }
    double width = BehaviorReflection.invokeVirtual(Double.TYPE, SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(render, "plot", false)), "org.campagnelab.metar.tables.structure.PlotBuilderStatement"), "virtual_estimateWidth_4842667988071989466", new Object[]{});
    return Double.toString(width / (SPropertyOperations.getInteger(SLinkOperations.getTarget(render, "style", false), "pixelsPerInch")));
  }

  public static Object propertyMacro_GetPropertyValue_4842667988072079168(final PropertyMacroContext _context) {
    SNode render = SNodeOperations.getAncestor(_context.getNode(), "org.campagnelab.metar.tables.structure.Render", false, false);
    if (isNotEmptyString(SPropertyOperations.getString(render, "height"))) {
      return SPropertyOperations.getString(render, "height");
    }

    double height = BehaviorReflection.invokeVirtual(Double.TYPE, SNodeOperations.getAncestor(SLinkOperations.getTarget(render, "plot", false), "org.campagnelab.metar.tables.structure.PlotBuilderStatement", false, false), "virtual_estimateHeight_4842667988071995771", new Object[]{});
    return Double.toString(height / SPropertyOperations.getInteger(SLinkOperations.getTarget(render, "style", false), "pixelsPerInch"));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893511923656(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "formula", true), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893511932586(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "formula", true), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return "\"" + SPropertyOperations.getString(SLinkOperations.getTarget(it, "col", false), "name") + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893512244615(final PropertyMacroContext _context) {
    return ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "formula", true), "y", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893512024087(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "formula", true), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode colRef) {
        return "\"" + ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(colRef) + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893512010244(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "formula", true), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893512007793(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "formula", true), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return "\"" + SPropertyOperations.getString(SLinkOperations.getTarget(it, "col", false), "name") + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893511557803(final PropertyMacroContext _context) {
    return Model_Behavior.call_getCleanModelName_2807244893511582582(SLinkOperations.getTarget(_context.getNode(), "model", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893507585514(final PropertyMacroContext _context) {
    return ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(SLinkOperations.getTarget(_context.getNode(), "y", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893507594517(final PropertyMacroContext _context) {
    // <node> 
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode x) {
        return ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(x);
      }
    }), "+");
    // <node> 
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514667734(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "inputTable", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514173344(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) _context.getVariable("formula")), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514173359(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(((SNode) _context.getVariable("formula")), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return "\"" + SPropertyOperations.getString(SLinkOperations.getTarget(it, "col", false), "name") + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514173391(final PropertyMacroContext _context) {
    return ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(SLinkOperations.getTarget(((SNode) _context.getVariable("formula")), "y", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514173404(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(((SNode) _context.getVariable("formula")), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode colRef) {
        return "\"" + ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(colRef) + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514173432(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(((SNode) _context.getVariable("formula")), "y", true), "col", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893514173447(final PropertyMacroContext _context) {
    return IterableUtils.join(ListSequence.fromList(SLinkOperations.getTargets(((SNode) _context.getVariable("formula")), "predictors", true)).select(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return "\"" + SPropertyOperations.getString(SLinkOperations.getTarget(it, "col", false), "name") + "\"";
      }
    }), ",");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893515316778(final PropertyMacroContext _context) {
    return FutureTable_Behavior.call_getCleanTableName_4166618652720345586(SLinkOperations.getTarget(_context.getNode(), "table", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893515326875(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "inputTable", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893510499695(final PropertyMacroContext _context) {
    return FutureTable_Behavior.call_getCleanTableName_4166618652720345586(SLinkOperations.getTarget(_context.getNode(), "table", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893510516687(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "columnName");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893510504483(final PropertyMacroContext _context) {
    return Model_Behavior.call_getCleanModelName_2807244893511582582(SLinkOperations.getTarget(_context.getNode(), "model", false));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893515518334(final PropertyMacroContext _context) {
    return FutureTable_Behavior.call_getCleanTableName_4166618652720345586(SLinkOperations.getTarget(_context.getNode(), "table", true));
  }

  public static Object propertyMacro_GetPropertyValue_2807244893515534291(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "table", true), "id");
  }

  public static Object propertyMacro_GetPropertyValue_2807244893515511094(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_6070133740820404926(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_229475681291068172(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(ColumnRef_Behavior.call_getTable_229475681291125658(SLinkOperations.getTarget(_context.getNode(), "ColumnRef", true)), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_6070133740820413506(final PropertyMacroContext _context) {
    return ColumnRef_Behavior.call_getColumnName_229475681292662876(SLinkOperations.getTarget(_context.getNode(), "ColumnRef", true));

  }

  public static Object propertyMacro_GetPropertyValue_2312637992615388348(final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "style", false) != null) && ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "colors", false), "colors", true)).count() > 0) {
      StringBuilder builder = new StringBuilder();
      builder.append("col=c(");
      for (SNode ref : ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "colors", false), "colors", true))) {
        builder.append("\"").append(SPropertyOperations.getString(SLinkOperations.getTarget(ref, "color", false), "name")).append("\",");
      }
      String out = builder.toString();
      out = out.substring(0, out.length() - 1);
      return out + "),";
    } else {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_6070133740820410840(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getPath_8016431400518331231(SLinkOperations.getTarget(_context.getNode(), "plot", true));
  }

  public static Object propertyMacro_GetPropertyValue_6070133740820477669(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_6070133740820481398(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SNodeOperations.getAncestor(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "ColumnRef", true), "col", false), "org.campagnelab.metar.tables.structure.Table", false, false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_4977909310693684829(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_8016431400514006106(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_4166618652719892520(final PropertyMacroContext _context) {
    return MacrosFactory.getGlobal().expandPath("${org.campagnelab.hta.results_dir}");
  }

  public static Object propertyMacro_GetPropertyValue_8016431400514009759(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "path");
  }

  public static Object propertyMacro_GetPropertyValue_8031339867735055323(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "separator");
  }

  public static Object propertyMacro_GetPropertyValue_8031339867734638773(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean(_context.getNode(), "withQuotes") ? "TRUE" : "FALSE");
  }

  public static Object propertyMacro_GetPropertyValue_6070133740826980103(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_6070133740826980119(final PropertyMacroContext _context) {
    StringBuilder builder = new StringBuilder();
    for (SNode ref : ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "ColumnRefs", true))) {
      builder.append("c(").append(NameHelper.RName(SPropertyOperations.getString(SNodeOperations.getAncestor(SLinkOperations.getTarget(ref, "col", false), "org.campagnelab.metar.tables.structure.Table", false, false), "name"))).append("$").append(ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(ref)).append("),");
    }
    String out = builder.toString();
    return out.substring(0, out.length() - 1);
  }

  public static Object propertyMacro_GetPropertyValue_2312637992596216066(final PropertyMacroContext _context) {
    StringBuilder builder = new StringBuilder();
    for (SNode ref : ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "ColumnRefs", true))) {
      builder.append("\"").append(ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(ref)).append("\",");
    }
    String out = builder.toString();
    return out.substring(0, out.length() - 1);
  }

  public static Object propertyMacro_GetPropertyValue_2312637992612587889(final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "style", false) != null) && ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "colors", false), "colors", true)).count() > 0) {
      StringBuilder builder = new StringBuilder();
      builder.append("col=c(");
      int index = 0;
      for (SNode ref : ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "ColumnRefs", true))) {
        builder.append("\"").append(SPropertyOperations.getString(SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "colors", false), "colors", true)).getElement(index), "color", false), "name")).append("\",");
        index = (index + 1) % ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "colors", false), "colors", true)).count();
      }
      String out = builder.toString();
      out = out.substring(0, out.length() - 1);
      return out + "),";
    } else {
      return "";
    }

  }

  public static Object propertyMacro_GetPropertyValue_6070133740826980145(final PropertyMacroContext _context) {
    return Plot_Behavior.call_getPath_8016431400518331231(SLinkOperations.getTarget(_context.getNode(), "plot", true));
  }

  public static Object propertyMacro_GetPropertyValue_6070133740826980159(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "id");
  }

  public static Object propertyMacro_GetPropertyValue_6070133740826980168(final PropertyMacroContext _context) {
    return "";
  }

  public static Object propertyMacro_GetPropertyValue_6070133740826980191(final PropertyMacroContext _context) {
    return ((SNode) _context.getNode()).getNodeId().toString();
  }

  public static Object propertyMacro_GetPropertyValue_6583618001727205788(final PropertyMacroContext _context) {
    return NameHelper.RName(SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name"));
  }

  public static Object propertyMacro_GetPropertyValue_6583618001727226402(final PropertyMacroContext _context) {
    if (LOG.isInfoEnabled()) {
      LOG.info("column=" + SLinkOperations.getTarget(_context.getNode(), "column", true));
    }
    return ColumnRef_Behavior.call_getCleanColumnName_2807244893512039175(SLinkOperations.getTarget(_context.getNode(), "column", true));
  }

  public static Object propertyMacro_GetPropertyValue_4067230457182267927(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "text");
  }

  public static boolean ifMacro_Condition_1549006859295113839(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", false), "table", false), "columns", true)).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode column) {
        return ListSequence.fromList(SLinkOperations.getTargets(AttributeOperations.getAttribute(column, new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation")), "groups", true)).any(new IWhereFilter<SNode>() {
          public boolean accept(SNode group) {
            return "ID".equals(SPropertyOperations.getString(SLinkOperations.getTarget(group, "columnGroup", false), "name"));
          }
        });
      }
    });
  }

  public static boolean ifMacro_Condition_5703306641533761565(final IfMacroContext _context) {
    return true;
    // <node> 
  }

  public static boolean ifMacro_Condition_5703306641529057522(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "annotations", true) != null);
  }

  public static boolean ifMacro_Condition_2814838647966786236(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "annotations", true) != null);
  }

  public static boolean ifMacro_Condition_6001041468487572972(final IfMacroContext _context) {
    return false;
  }

  public static boolean ifMacro_Condition_8286430004408199559(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "xRange", true) != null);
  }

  public static boolean ifMacro_Condition_8286430004408210438(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "yRange", true) != null);
  }

  public static boolean ifMacro_Condition_3442436599519404533(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "groupBy", true) != null);
  }

  public static boolean ifMacro_Condition_4842667988068041272(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "xRange", true) != null);
  }

  public static boolean ifMacro_Condition_4842667988068043258(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "style", false), "yRange", true) != null);
  }

  public static boolean ifMacro_Condition_6583618001733606651(final IfMacroContext _context) {
    return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<String>>) ((Class) Object.class), _context.getNode(), "virtual_bioConductorDependencies_6583618001733614174", new Object[]{})).isNotEmpty();
  }

  public static SNode sourceNodeQuery_7783277237109349553(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "rowFilter", true), "org.campagnelab.metar.tables.structure.FilterWithExpression"), "filter", true);
  }

  public static SNode sourceNodeQuery_772483346259559062(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "statements", true);
  }

  public static SNode sourceNodeQuery_4842667988071956352(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "output", true);
  }

  public static SNode sourceNodeQuery_2807244893508634567(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "formula", true);
  }

  public static Object templateArgumentQuery_2807244893514263516(final TemplateQueryContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(SNodeOperations.getParent(SLinkOperations.getTarget(_context.getNode(), "model", false)), "org.campagnelab.metar.tables.structure.Formula", false, new String[]{})).first();
  }

  public static Iterable<SNode> sourceNodesQuery_3402264987267873052(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transformations", true);
  }

  public static Iterable<SNode> sourceNodesQuery_2826789978070126322(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "inputTables", true);
  }

  public static Iterable<SNode> sourceNodesQuery_5703306641529033578(final SourceSubstituteMacroNodesContext _context) {
    final Iterable<String> usageNames = BehaviorReflection.invokeVirtual((Class<Iterable<String>>) ((Class) Object.class), SLinkOperations.getTarget(_context.getNode(), "annotations", true), "virtual_getColumnUsageNames_5703306641526703176", new Object[]{TableRef_Behavior.call_getReferencedUsageTypes_5703306641530424876(SLinkOperations.getTarget(_context.getNode(), "table", true))});
    Iterable<SNode> result = ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "columns", true)).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return ListSequence.fromList(SLinkOperations.getTargets(AttributeOperations.getAttribute(it, new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation")), "groups", true)).where(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return (SLinkOperations.getTarget(it, "columnGroup", false) != null);
          }
        }).select(new ISelector<SNode, SNode>() {
          public SNode select(SNode it) {
            return SLinkOperations.getTarget(it, "columnGroup", false);
          }
        }).translate(new ITranslator2<SNode, SNode>() {
          public Iterable<SNode> translate(SNode it) {
            return SLinkOperations.getTargets(it, "usesRefs", true);
          }
        }).where(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return (SLinkOperations.getTarget(it, "usage", false) != null);
          }
        }).select(new ISelector<SNode, SNode>() {
          public SNode select(SNode it) {
            return SLinkOperations.getTarget(it, "usage", false);
          }
        });
      }
    }).distinct().where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return Sequence.fromIterable(usageNames).contains(SPropertyOperations.getString(it, "name"));
      }
    }).sort(new ISelector<SNode, Integer>() {
      public Integer select(SNode usage) {
        return Sequence.fromIterable(usageNames).indexOf(SPropertyOperations.getString(usage, "name"));
      }
    }, true);
    _context.putSessionObject("lastIndex", Sequence.fromIterable(result).count());
    return result;

  }

  public static Iterable<SNode> sourceNodesQuery_3687343996977966817(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(Multiplot_Behavior.call_getPlotsInRowOrder_4842667988068961113(_context.getNode())).subListSequence(0, SPropertyOperations.getInteger(_context.getNode(), "numColumns") * SPropertyOperations.getInteger(_context.getNode(), "numRows"));
  }

  public static Iterable<SNode> sourceNodesQuery_4067230457182238075(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(SLinkOperations.getTargets(_context.getNode(), "commentedStatement", true), "jetbrains.mps.baseLanguage.structure.TextCommentPart");
  }

  public static void mappingScript_CodeBlock_4166618652720374776(final MappingScriptContext _context) {
    // increment the ids for future tables so that columns names never reuse the same filename 
    // <node> 
    // <node> 
  }

  public static Object insertMacro_varValue_5703306641531810262(final TemplateQueryContext _context) {
    return _context.getNode();
  }

  public static Object insertMacro_varValue_2807244893508417362(final TemplateQueryContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "table", true), "table", false), "name");
  }

  protected static Logger LOG = LogManager.getLogger(QueriesGenerated.class);

  private static boolean eq_x583g4_a0a0a0a0a0a0a0a0a0a0a0a0a8a71(Object a, Object b) {
    return (a != null ? a.equals(b) : a == b);
  }

  private static boolean eq_x583g4_a0a0a0a0a0a0a0a0a0a1a0a0a0a4a12(Object a, Object b) {
    return (a != null ? a.equals(b) : a == b);
  }

  private static boolean eq_x583g4_a0a0a0a0a0a0a0a0a0a0a1a0a0a0a4a12(Object a, Object b) {
    return (a != null ? a.equals(b) : a == b);
  }

  private static boolean eq_x583g4_a0a0a0a0a0a0a0a0a0a0a42(Object a, Object b) {
    return (a != null ? a.equals(b) : a == b);
  }

  private static boolean eq_x583g4_a0a0a0a0a0a0a0a0a0a1a73(Object a, Object b) {
    return (a != null ? a.equals(b) : a == b);
  }

  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
