package org.campagnelab.metar.edgeR.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class EdgeRTest_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "destinationTable", SConceptOperations.createNewNode("org.campagnelab.metar.tables.structure.FutureTable", null), true);
    SLinkOperations.setTarget(thisNode, "modelFormula", SConceptOperations.createNewNode("org.campagnelab.metar.edgeR.structure.GroupFormula", null), true);
    SLinkOperations.setTarget(thisNode, "dispersionMethod", SConceptOperations.createNewNode("org.campagnelab.metar.edgeR.structure.CommonDispersion", null), true);
    SLinkOperations.setTarget(thisNode, "contrasts", SConceptOperations.createNewNode("org.campagnelab.metar.edgeR.structure.GroupUsageExpression", null), true);
  }
}
