package org.campagnelab.metar.edgeR.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class GroupExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public GroupExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.edgeR.structure.GroupExpression";
  }
}
