package org.campagnelab.metar.edgeR.behavior;

/*Generated by MPS */


public class GroupRef_BehaviorDescriptor extends GroupExpression_BehaviorDescriptor {
  public GroupRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.edgeR.structure.GroupRef";
  }
}
