package org.campagnelab.metar.edgeR.behavior;

/*Generated by MPS */


public class Times_BehaviorDescriptor extends BinaryExpression_BehaviorDescriptor {
  public Times_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.metar.edgeR.structure.Times";
  }
}
