package org.campagnelab.editor.images.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import java.util.Collection;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import java.util.Collections;
import jetbrains.mps.generator.runtime.NodeWeaveFacility;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class Template_reduce_image extends TemplateDeclarationBase {

  public Template_reduce_image() {
  }

  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688842254");
  }
  protected SNode applyPart0(@NotNull final TemplateContext contextNoLabel) throws GenerationException {
    final TemplateExecutionEnvironment environment = contextNoLabel.getEnvironment();
    final TemplateContext context = contextNoLabel.subContext("cellFactory.factoryMethod");
    final SNode tnode1 = environment.createOutputNode(myConcepts[0]);
    try {
      SNodeAccessUtil.setProperty(tnode1, myProperties[0], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_3219955940688849735(new PropertyMacroContext(context, "_cell_factory_method_", propertyMacro_yujq03_c0a0c0a0d0e))));
      TemplateContext context1 = context.subContext();
      {
        final SNode tnode2 = environment.createOutputNode(myConcepts[1]);
        try {
          tnode2.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode2, PersistenceFacade.getInstance().createModelReference("1ed103c3-3aa6-49b7-9c21-6765ee11f224/java:jetbrains.mps.openapi.editor.cells(MPS.Editor/)"), PersistenceFacade.getInstance().createNodeId("~EditorCell")));
        } finally {
        }
        tnode1.addChild(myAggregationLinks[0], tnode2);
        // TODO validate child 
      }
      {
        final SNode tnode3 = environment.createOutputNode(myConcepts[2]);
        try {
        } finally {
        }
        tnode1.addChild(myAggregationLinks[1], tnode3);
        // TODO validate child 
      }
      {
        final SNode tnode4 = environment.createOutputNode(myConcepts[3]);
        try {
          TemplateContext context2 = context1.subContext();
          {
            final SNode tnode5 = environment.createOutputNode(myConcepts[4]);
            try {
              TemplateContext context3 = context2.subContext();
              {
                final SNode tnode6 = environment.createOutputNode(myConcepts[5]);
                try {
                  environment.nodeCopied(context3, tnode6, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851684");
                  SNodeAccessUtil.setProperty(tnode6, myProperties[0], "imagePath");
                  TemplateContext context4 = context3.subContext();
                  {
                    final SNode tnode7 = environment.createOutputNode(myConcepts[6]);
                    try {
                    } finally {
                    }
                    tnode6.addChild(myAggregationLinks[2], tnode7);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode8 = environment.createOutputNode(myConcepts[7]);
                    try {
                      SNodeAccessUtil.setProperty(tnode8, myProperties[1], "");
                    } finally {
                    }
                    tnode6.addChild(myAggregationLinks[3], tnode8);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode5.addChild(myAggregationLinks[4], tnode6);
                // TODO validate child 
              }
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode5);
            // TODO validate child 
          }
          {
            final SNode tnode9 = environment.createOutputNode(myConcepts[4]);
            try {
              TemplateContext context5 = context2.subContext();
              {
                final SNode tnode10 = environment.createOutputNode(myConcepts[5]);
                try {
                  SNodeAccessUtil.setProperty(tnode10, myProperties[0], "imageModule");
                  TemplateContext context6 = context5.subContext();
                  {
                    final SNode tnode11 = environment.createOutputNode(myConcepts[1]);
                    try {
                      tnode11.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode11, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.module(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SModule")));
                    } finally {
                    }
                    tnode10.addChild(myAggregationLinks[2], tnode11);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode12 = environment.createOutputNode(myConcepts[8]);
                    try {
                    } finally {
                    }
                    tnode10.addChild(myAggregationLinks[3], tnode12);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode9.addChild(myAggregationLinks[4], tnode10);
                // TODO validate child 
              }
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode9);
            // TODO validate child 
          }
          {
            final SNode tnode13 = environment.createOutputNode(myConcepts[9]);
            try {
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode13);
            // TODO validate child 
          }
          {
            Collection<SNode> tlist14 = null;
            {
              final SNode switchInput14 = QueriesGenerated.sourceNodeQuery_5841812207174785409(new SourceSubstituteMacroNodeContext(context2, switchMacroRef_yujq03_b0a0a0a1a4a1a4a3a4));
              if (switchInput14 == null) {
                tlist14 = Collections.emptyList();
              } else {
                TemplateContext switchContext14;
                switchContext14 = context2.subContext(null, switchInput14);
                tlist14 = environment.trySwitch(templateSwitchNode_yujq03_a0a0c0a1a1a4a1a4a3a4, switchContext14);
                if (tlist14 == null) {
                  final SNode tnode15 = environment.createOutputNode(myConcepts[10]);
                  try {
                    TemplateContext context7 = context2.subContext();
                    {
                      final SNode tnode16 = environment.createOutputNode(myConcepts[11]);
                      try {
                        TemplateContext context8 = context7.subContext();
                        {
                          final SNode tnode17 = environment.createOutputNode(myConcepts[12]);
                          try {
                            TemplateContext context9 = context8.subContext();
                            {
                              final SNode tnode18 = environment.createOutputNode(myConcepts[8]);
                              try {
                              } finally {
                              }
                              tnode17.addChild(myAggregationLinks[6], tnode18);
                              // TODO validate child 
                            }
                            {
                              final SNode tnode19 = environment.createOutputNode(myConcepts[8]);
                              try {
                              } finally {
                              }
                              tnode17.addChild(myAggregationLinks[6], tnode19);
                              // TODO validate child 
                            }
                          } finally {
                          }
                          tnode16.addChild(myAggregationLinks[7], tnode17);
                          // TODO validate child 
                        }
                        {
                          final SNode tnode20 = environment.createOutputNode(myConcepts[12]);
                          try {
                            TemplateContext context10 = context8.subContext();
                            {
                              final SNode tnode21 = environment.createOutputNode(myConcepts[13]);
                              try {
                                tnode21.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode21, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("1672594678668584490")));
                              } finally {
                              }
                              tnode20.addChild(myAggregationLinks[6], tnode21);
                              // TODO validate child 
                            }
                            {
                              final SNode tnode22 = environment.createOutputNode(myConcepts[13]);
                              try {
                                tnode22.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode22, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("6250046037307796326")));
                              } finally {
                              }
                              tnode20.addChild(myAggregationLinks[6], tnode22);
                              // TODO validate child 
                            }
                          } finally {
                          }
                          tnode16.addChild(myAggregationLinks[8], tnode20);
                          // TODO validate child 
                        }
                      } finally {
                      }
                      tnode15.addChild(myAggregationLinks[9], tnode16);
                      // TODO validate child 
                    }
                  } finally {
                  }
                  if (tnode15 != null) {
                    tlist14 = TemplateUtil.singletonList(tnode15);
                  }
                }
              }
            }
            for (SNode child23 : TemplateUtil.asNotNull(tlist14)) {
              tnode4.addChild(myAggregationLinks[5], child23);
            }
            // TODO validate child 
          }
          {
            final SNode tnode24 = environment.createOutputNode(myConcepts[9]);
            try {
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode24);
            // TODO validate child 
          }
          {
            final SNode tnode25 = environment.createOutputNode(myConcepts[4]);
            try {
              TemplateContext context11 = context2.subContext();
              {
                final SNode tnode26 = environment.createOutputNode(myConcepts[5]);
                try {
                  environment.nodeCopied(context11, tnode26, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700");
                  SNodeAccessUtil.setProperty(tnode26, myProperties[2], "false");
                  SNodeAccessUtil.setProperty(tnode26, myProperties[0], "image");
                  TemplateContext context12 = context11.subContext();
                  {
                    final SNode tnode27 = environment.createOutputNode(myConcepts[1]);
                    try {
                      tnode27.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode27, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5534405333772914929")));
                    } finally {
                    }
                    tnode26.addChild(myAggregationLinks[2], tnode27);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode25.addChild(myAggregationLinks[4], tnode26);
                // TODO validate child 
              }
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode25);
            // TODO validate child 
          }
          {
            final SNode tnode28 = environment.createOutputNode(myConcepts[14]);
            try {
              TemplateContext context13 = context2.subContext();
              {
                final SNode tnode29 = environment.createOutputNode(myConcepts[3]);
                try {
                  TemplateContext context14 = context13.subContext();
                  {
                    final SNode tnode30 = environment.createOutputNode(myConcepts[10]);
                    try {
                      TemplateContext context15 = context14.subContext();
                      {
                        final SNode tnode31 = environment.createOutputNode(myConcepts[11]);
                        try {
                          TemplateContext context16 = context15.subContext();
                          {
                            final SNode tnode32 = environment.createOutputNode(myConcepts[15]);
                            try {
                              TemplateContext context17 = context16.subContext();
                              {
                                final SNode tnode33 = environment.createOutputNode(myConcepts[16]);
                                try {
                                  tnode33.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode33, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5534405333774307914")));
                                  TemplateContext context18 = context17.subContext();
                                  {
                                    final SNode tnode34 = environment.createOutputNode(myConcepts[13]);
                                    try {
                                      environment.resolveInTemplateLater(tnode34, myAssociationLinks[1], templateNode_yujq03_c0a0a1a2a1a1a1a1a1a1a1a1a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851684", "imagePath", context18);
                                    } finally {
                                    }
                                    tnode33.addChild(myAggregationLinks[10], tnode34);
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                tnode32.addChild(myAggregationLinks[11], tnode33);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode31.addChild(myAggregationLinks[7], tnode32);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode35 = environment.createOutputNode(myConcepts[13]);
                            try {
                              environment.resolveInTemplateLater(tnode35, myAssociationLinks[1], templateNode_yujq03_c0a0a1a2a1a1a1a1a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700", "image", context16);
                            } finally {
                            }
                            tnode31.addChild(myAggregationLinks[8], tnode35);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode30.addChild(myAggregationLinks[9], tnode31);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode29.addChild(myAggregationLinks[5], tnode30);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode36 = environment.createOutputNode(myConcepts[4]);
                    try {
                      TemplateContext context19 = context14.subContext();
                      {
                        final SNode tnode37 = environment.createOutputNode(myConcepts[5]);
                        try {
                          environment.nodeCopied(context19, tnode37, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851738");
                          SNodeAccessUtil.setProperty(tnode37, myProperties[0], "editorCell");
                          TemplateContext context20 = context19.subContext();
                          {
                            final SNode tnode38 = environment.createOutputNode(myConcepts[1]);
                            try {
                              tnode38.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode38, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("3288318341320524274")));
                            } finally {
                            }
                            tnode37.addChild(myAggregationLinks[2], tnode38);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode39 = environment.createOutputNode(myConcepts[17]);
                            try {
                              tnode39.setReference(myAssociationLinks[3], SReference.create(myAssociationLinks[3], tnode39, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("3288318341320524274")));
                              tnode39.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode39, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("3288318341320526938")));
                              TemplateContext context21 = context20.subContext();
                              {
                                final SNode tnode40 = environment.createOutputNode(myConcepts[18]);
                                try {
                                  tnode40.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode40, PersistenceFacade.getInstance().createModelReference("r:8ff33705-85bf-4855-805c-06d68fbe233c(jetbrains.mps.editor.runtime.descriptor)"), PersistenceFacade.getInstance().createNodeId("7869544664116130639")));
                                } finally {
                                }
                                tnode39.addChild(myAggregationLinks[10], tnode40);
                                // TODO validate child 
                              }
                              {
                                final SNode tnode41 = environment.createOutputNode(myConcepts[13]);
                                try {
                                  tnode41.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode41, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("8877820395434551504")));
                                } finally {
                                }
                                tnode39.addChild(myAggregationLinks[10], tnode41);
                                // TODO validate child 
                              }
                              {
                                final SNode tnode42 = environment.createOutputNode(myConcepts[13]);
                                try {
                                  environment.resolveInTemplateLater(tnode42, myAssociationLinks[1], templateNode_yujq03_c0a0a1a5a1a4a1a1a1a2a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700", "image", context21);
                                } finally {
                                }
                                tnode39.addChild(myAggregationLinks[10], tnode42);
                                // TODO validate child 
                              }
                              {
                                final SNode tnode43 = environment.createOutputNode(myConcepts[13]);
                                try {
                                  environment.resolveInTemplateLater(tnode43, myAssociationLinks[1], templateNode_yujq03_c0a0a1a6a1a4a1a1a1a2a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851684", "imagePath", context21);
                                } finally {
                                }
                                tnode39.addChild(myAggregationLinks[10], tnode43);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode37.addChild(myAggregationLinks[3], tnode39);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode36.addChild(myAggregationLinks[4], tnode37);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode29.addChild(myAggregationLinks[5], tnode36);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode44 = environment.createOutputNode(myConcepts[10]);
                    try {
                      TemplateContext context22 = context14.subContext();
                      {
                        final SNode tnode45 = environment.createOutputNode(myConcepts[19]);
                        try {
                          TemplateContext context23 = context22.subContext();
                          {
                            final SNode tnode46 = environment.createOutputNode(myConcepts[13]);
                            try {
                              environment.resolveInTemplateLater(tnode46, myAssociationLinks[1], templateNode_yujq03_c0a0a1a1a1a1a1a3a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700", "image", context23);
                            } finally {
                            }
                            tnode45.addChild(myAggregationLinks[12], tnode46);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode47 = environment.createOutputNode(myConcepts[20]);
                            try {
                              tnode47.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode47, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5534405333775179449")));
                              TemplateContext context24 = context23.subContext();
                              {
                                final SNode tnode48 = environment.createOutputNode(myConcepts[13]);
                                try {
                                  environment.resolveInTemplateLater(tnode48, myAssociationLinks[1], templateNode_yujq03_c0a0a1a2a1a2a1a1a1a3a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851738", "editorCell", context24);
                                } finally {
                                }
                                tnode47.addChild(myAggregationLinks[10], tnode48);
                                // TODO validate child 
                              }
                              {
                                final SNode tnode49 = environment.createOutputNode(myConcepts[19]);
                                try {
                                  TemplateContext context25 = context24.subContext();
                                  {
                                    final SNode tnode50 = environment.createOutputNode(myConcepts[21]);
                                    try {
                                      TemplateContext context26 = context25.subContext();
                                      {
                                        final SNode tnode51 = environment.createOutputNode(myConcepts[19]);
                                        try {
                                          TemplateContext context27 = context26.subContext();
                                          {
                                            final SNode tnode52 = environment.createOutputNode(myConcepts[13]);
                                            try {
                                              tnode52.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode52, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("8877820395434551504")));
                                            } finally {
                                            }
                                            tnode51.addChild(myAggregationLinks[12], tnode52);
                                            // TODO validate child 
                                          }
                                          {
                                            final SNode tnode53 = environment.createOutputNode(myConcepts[22]);
                                            try {
                                            } finally {
                                            }
                                            tnode51.addChild(myAggregationLinks[13], tnode53);
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        tnode50.addChild(myAggregationLinks[14], tnode51);
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    tnode49.addChild(myAggregationLinks[12], tnode50);
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode54 = environment.createOutputNode(myConcepts[20]);
                                    try {
                                      tnode54.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode54, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.model(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SModel.getRepository():org.jetbrains.mps.openapi.module.SRepository")));
                                    } finally {
                                    }
                                    tnode49.addChild(myAggregationLinks[13], tnode54);
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                tnode47.addChild(myAggregationLinks[10], tnode49);
                                // TODO validate child 
                              }
                              {
                                final SNode tnode55 = environment.createOutputNode(myConcepts[19]);
                                try {
                                  TemplateContext context28 = context24.subContext();
                                  {
                                    final SNode tnode56 = environment.createOutputNode(myConcepts[21]);
                                    try {
                                      TemplateContext context29 = context28.subContext();
                                      {
                                        final SNode tnode57 = environment.createOutputNode(myConcepts[19]);
                                        try {
                                          TemplateContext context30 = context29.subContext();
                                          {
                                            final SNode tnode58 = environment.createOutputNode(myConcepts[13]);
                                            try {
                                              tnode58.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode58, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("8877820395434551504")));
                                            } finally {
                                            }
                                            tnode57.addChild(myAggregationLinks[12], tnode58);
                                            // TODO validate child 
                                          }
                                          {
                                            final SNode tnode59 = environment.createOutputNode(myConcepts[22]);
                                            try {
                                            } finally {
                                            }
                                            tnode57.addChild(myAggregationLinks[13], tnode59);
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        tnode56.addChild(myAggregationLinks[14], tnode57);
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    tnode55.addChild(myAggregationLinks[12], tnode56);
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode60 = environment.createOutputNode(myConcepts[20]);
                                    try {
                                      tnode60.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode60, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.model(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SModel.getModule():org.jetbrains.mps.openapi.module.SModule")));
                                    } finally {
                                    }
                                    tnode55.addChild(myAggregationLinks[13], tnode60);
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                tnode47.addChild(myAggregationLinks[10], tnode55);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode45.addChild(myAggregationLinks[13], tnode47);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode44.addChild(myAggregationLinks[9], tnode45);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode29.addChild(myAggregationLinks[5], tnode44);
                    // TODO validate child 
                  }
                  {
                    Collection<SNode> tlist61 = null;
                    try {
                      try {
                        tlist61 = environment.applyTemplate(new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "5170495790389304146"), new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851745"), context14);
                      } finally {
                      }

                    } finally {
                    }
                    for (SNode child62 : TemplateUtil.asNotNull(tlist61)) {
                      tnode29.addChild(myAggregationLinks[5], child62);
                    }
                    // TODO validate child 
                  }
                  {
                    Collection<SNode> tlist63 = null;
                    tlist63 = environment.applyTemplate(new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "6287772348368334582"), new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851749"), context14);
                    for (SNode child64 : TemplateUtil.asNotNull(tlist63)) {
                      tnode29.addChild(myAggregationLinks[5], child64);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode65 = environment.createOutputNode(myConcepts[23]);
                    try {
                      TemplateContext context31 = context14.subContext();
                      {
                        final SNode tnode66 = environment.createOutputNode(myConcepts[13]);
                        try {
                          environment.resolveInTemplateLater(tnode66, myAssociationLinks[1], templateNode_yujq03_c0a0a1a1a1a6a1a1a1a7a1a4a3a4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851738", "editorCell", context31);
                        } finally {
                        }
                        tnode65.addChild(myAggregationLinks[15], tnode66);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode29.addChild(myAggregationLinks[5], tnode65);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode28.addChild(myAggregationLinks[16], tnode29);
                // TODO validate child 
              }
              {
                final SNode tnode67 = environment.createOutputNode(myConcepts[24]);
                try {
                  TemplateContext context32 = context13.subContext();
                  {
                    final SNode tnode68 = environment.createOutputNode(myConcepts[5]);
                    try {
                      SNodeAccessUtil.setProperty(tnode68, myProperties[0], "npe");
                      TemplateContext context33 = context32.subContext();
                      {
                        final SNode tnode69 = environment.createOutputNode(myConcepts[1]);
                        try {
                          tnode69.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode69, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.lang(JDK/)"), PersistenceFacade.getInstance().createNodeId("~NullPointerException")));
                        } finally {
                        }
                        tnode68.addChild(myAggregationLinks[2], tnode69);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode67.addChild(myAggregationLinks[17], tnode68);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode70 = environment.createOutputNode(myConcepts[3]);
                    try {
                    } finally {
                    }
                    tnode67.addChild(myAggregationLinks[18], tnode70);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode28.addChild(myAggregationLinks[19], tnode67);
                // TODO validate child 
              }
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode28);
            // TODO validate child 
          }
          {
            final SNode tnode71 = environment.createOutputNode(myConcepts[23]);
            try {
              TemplateContext context34 = context2.subContext();
              {
                final SNode tnode72 = environment.createOutputNode(myConcepts[8]);
                try {
                } finally {
                }
                tnode71.addChild(myAggregationLinks[15], tnode72);
                // TODO validate child 
              }
            } finally {
            }
            tnode4.addChild(myAggregationLinks[5], tnode71);
            // TODO validate child 
          }
        } finally {
        }
        tnode1.addChild(myAggregationLinks[20], tnode4);
        // TODO validate child 
      }
    } finally {
    }
    environment.registerLabel(contextNoLabel.getInput(), tnode1, "cellFactory.factoryMethod");
    return tnode1;
  }
  @Override
  public Collection<SNode> apply(@NotNull TemplateExecutionEnvironment environment, @NotNull TemplateContext context) throws GenerationException {
    return TemplateUtil.singletonList(applyPart0(context));
  }

  @Override
  public Collection<SNode> weave(@NotNull NodeWeaveFacility.WeaveContext weaveContext, @NotNull NodeWeaveFacility weaveSupport) throws GenerationException {
    final TemplateContext templateContext = weaveSupport.getTemplateContext();
    SNode tnodepart0 = applyPart0(templateContext);
    weaveSupport.weaveNode(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101d9d3ca30L, 0x4a9a46de59132803L, "member"), tnodepart0);
    return TemplateUtil.singletonList(tnodepart0);
  }
  @Override
  protected SConcept[] initConcepts() {
    SConcept[] rv = new SConcept[25];
    rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b21dL, "InstanceMethodDeclaration");
    rv[1] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x101de48bf9eL, "ClassifierType");
    rv[2] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x10af9586f0cL, "PrivateVisibility");
    rv[3] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b200L, "StatementList");
    rv[4] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc67c7f0L, "LocalVariableDeclarationStatement");
    rv[5] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc67c7efL, "LocalVariableDeclaration");
    rv[6] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x11d47da71ecL, "StringType");
    rv[7] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf93d565d10L, "StringLiteral");
    rv[8] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf940cd6167L, "NullLiteral");
    rv[9] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b215L, "Statement");
    rv[10] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b213L, "ExpressionStatement");
    rv[11] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8c77f1e96L, "AssignmentExpression");
    rv[12] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xa247e09e243545baL, 0xb8d207e93feba96aL, "jetbrains.mps.baseLanguage.tuples"), 0x12071708c13L, "IndexedTupleLiteral");
    rv[13] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8c77f1e98L, "VariableReference");
    rv[14] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x10f383e6771L, "TryCatchStatement");
    rv[15] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x10ab8473cc5L, "GenericNewExpression");
    rv[16] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x11a59b0fbceL, "ClassCreator");
    rv[17] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xfbbebabf09L, "StaticMethodCall");
    rv[18] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x6c6b6a1e379f9404L, "LocalMethodCall");
    rv[19] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x116b46a08c4L, "DotExpression");
    rv[20] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x118154a6332L, "InstanceMethodCallOperation");
    rv[21] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, "jetbrains.mps.lang.smodel"), 0x10aaf6d7435L, "SemanticDowncastExpression");
    rv[22] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, "jetbrains.mps.lang.smodel"), 0x10a2e126334L, "Node_GetModelOperation");
    rv[23] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc67c7feL, "ReturnStatement");
    rv[24] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x10f39a56e2fL, "CatchClause");
    return rv;
  }
  @Override
  protected SProperty[] initProperties() {
    SProperty[] rv = new SProperty[3];
    rv[0] = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    rv[1] = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value");
    rv[2] = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal");
    return rv;
  }
  @Override
  protected SReferenceLink[] initAssociationLinks() {
    SReferenceLink[] rv = new SReferenceLink[4];
    rv[0] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier");
    rv[1] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration");
    rv[2] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration");
    rv[3] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept");
    return rv;
  }
  @Override
  protected SContainmentLink[] initAggregationLinks() {
    SContainmentLink[] rv = new SContainmentLink[21];
    rv[0] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1fdL, "returnType");
    rv[1] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x112670d273fL, 0x112670d886aL, "visibility");
    rv[2] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type");
    rv[3] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer");
    rv[4] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration");
    rv[5] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement");
    rv[6] = MetaAdapterFactory.getContainmentLink(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, 0x1207171832eL, "component");
    rv[7] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue");
    rv[8] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue");
    rv[9] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression");
    rv[10] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument");
    rv[11] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator");
    rv[12] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand");
    rv[13] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation");
    rv[14] = MetaAdapterFactory.getContainmentLink(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x10aaf6d7435L, 0x10aaf6f6e81L, "leftExpression");
    rv[15] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression");
    rv[16] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, 0x10f383e83d4L, "body");
    rv[17] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, 0x10f39a6a2f1L, "throwable");
    rv[18] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, 0x10f39a6a2f2L, "catchBody");
    rv[19] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, 0x10f39a8ba1fL, "catchClause");
    rv[20] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1ffL, "body");
    return rv;
  }
  private static SNodePointer propertyMacro_yujq03_c0a0c0a0d0e = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688849734");
  private static SNodePointer switchMacroRef_yujq03_b0a0a0a1a4a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5841812207174784809");
  private static SNodePointer templateSwitchNode_yujq03_a0a0c0a1a1a4a1a4a3a4 = new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "5841812207174733785");
  private static SNodePointer templateNode_yujq03_c0a0a1a2a1a1a1a1a1a1a1a1a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3873701307954155196");
  private static SNodePointer templateNode_yujq03_c0a0a1a2a1a1a1a1a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3873701307954141223");
  private static SNodePointer templateNode_yujq03_c0a0a1a5a1a4a1a1a1a2a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851743");
  private static SNodePointer templateNode_yujq03_c0a0a1a6a1a4a1a1a1a2a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3288318341320836426");
  private static SNodePointer templateNode_yujq03_c0a0a1a1a1a1a1a3a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5534405333775252450");
  private static SNodePointer templateNode_yujq03_c0a0a1a2a1a2a1a1a1a3a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5534405333775254183");
  private static SNodePointer templateNode_yujq03_c0a0a1a1a1a6a1a1a1a7a1a4a3a4 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3873701307954160380");
}
