package org.campagnelab.editor.images.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import java.util.Collection;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import java.util.Collections;
import jetbrains.mps.generator.runtime.NodeWeaveFacility;

@Generated
public class Templatereduce__image extends TemplateDeclarationBase {
  public Templatereduce__image() {
  }
  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688842254");
  }
  protected SNode applyPart0(@NotNull final TemplateContext context) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    TemplateContext context1 = context.subContext("cellFactoryMethod");
    final SNode tnode2 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b21dL, "jetbrains.mps.baseLanguage.structure.InstanceMethodDeclaration"));
    try {
      environment.nodeCopied(context1, tnode2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849717");
      SNodeAccessUtil.setProperty(tnode2, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_3219955940688849735(new PropertyMacroContext(context1, "_cell_factory_method_", propertyMacro_2u1i0t_c0a0c0b0d0c))));
      TemplateContext context2 = context1.subContext();
      {
        final SNode tnode3 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
        try {
          environment.nodeCopied(context2, tnode3, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849718");
          tnode3.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode3, PersistenceFacade.getInstance().createModelReference("1ed103c3-3aa6-49b7-9c21-6765ee11f224/java:jetbrains.mps.openapi.editor.cells(MPS.Editor/)"), PersistenceFacade.getInstance().createNodeId("~EditorCell")));
        } finally {
        }
        if (tnode3 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1fdL, "returnType"), tnode3);
        }
        // TODO validate child 
      }
      {
        final SNode tnode4 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10af9586f0cL, "jetbrains.mps.baseLanguage.structure.PrivateVisibility"));
        try {
          environment.nodeCopied(context2, tnode4, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849719");
        } finally {
        }
        if (tnode4 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x112670d273fL, 0x112670d886aL, "visibility"), tnode4);
        }
        // TODO validate child 
      }
      {
        final SNode tnode5 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
        try {
          environment.nodeCopied(context2, tnode5, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849720");
          TemplateContext context5 = context2.subContext();
          {
            final SNode tnode6 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
            try {
              environment.nodeCopied(context5, tnode6, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851683");
              TemplateContext context6 = context5.subContext();
              {
                final SNode tnode7 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                try {
                  environment.nodeCopied(context6, tnode7, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851684");
                  SNodeAccessUtil.setProperty(tnode7, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "imagePath");
                  TemplateContext context7 = context6.subContext();
                  {
                    final SNode tnode8 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11d47da71ecL, "jetbrains.mps.baseLanguage.structure.StringType"));
                    try {
                      environment.nodeCopied(context7, tnode8, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851685");
                    } finally {
                    }
                    if (tnode8 != null) {
                      tnode7.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode8);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode9 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, "jetbrains.mps.baseLanguage.structure.StringLiteral"));
                    try {
                      environment.nodeCopied(context7, tnode9, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940692075270");
                      SNodeAccessUtil.setProperty(tnode9, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "");
                    } finally {
                    }
                    if (tnode9 != null) {
                      tnode7.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode9);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode7 != null) {
                  tnode6.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode7);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode6 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode6);
            }
            // TODO validate child 
          }
          {
            final SNode tnode10 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
            try {
              environment.nodeCopied(context5, tnode10, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174735172");
              TemplateContext context10 = context5.subContext();
              {
                final SNode tnode11 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                try {
                  environment.nodeCopied(context10, tnode11, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174735173");
                  SNodeAccessUtil.setProperty(tnode11, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "imageModule");
                  TemplateContext context11 = context10.subContext();
                  {
                    final SNode tnode12 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                    try {
                      environment.nodeCopied(context11, tnode12, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174735174");
                      tnode12.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode12, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.module()"), PersistenceFacade.getInstance().createNodeId("~SModule")));
                    } finally {
                    }
                    if (tnode12 != null) {
                      tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode12);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode13 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940cd6167L, "jetbrains.mps.baseLanguage.structure.NullLiteral"));
                    try {
                      environment.nodeCopied(context11, tnode13, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940692076269");
                    } finally {
                    }
                    if (tnode13 != null) {
                      tnode11.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode13);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode11 != null) {
                  tnode10.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode11);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode10 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode10);
            }
            // TODO validate child 
          }
          {
            final SNode tnode14 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b215L, "jetbrains.mps.baseLanguage.structure.Statement"));
            try {
              environment.nodeCopied(context5, tnode14, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940692072316");
            } finally {
            }
            if (tnode14 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode14);
            }
            // TODO validate child 
          }
          {
            Collection<SNode> tlist15 = null;
            {
              final SNode switchInput15 = QueriesGenerated.sourceNodeQuery_5841812207174785409(new SourceSubstituteMacroNodeContext(context5, switchMacroRef_2u1i0t_b0a0a0a1a5a1a5a3a2));
              if (switchInput15 == null) {
                tlist15 = Collections.emptyList();
              } else {
                TemplateContext switchContext15;
                switchContext15 = context5.subContext(null, switchInput15);
                tlist15 = environment.trySwitch(templateSwitchNode_2u1i0t_a0a0c0a1a1a5a1a5a3a2, switchContext15);
                if (tlist15 == null) {
                  final SNode tnode16 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                  try {
                    environment.nodeCopied(context5, tnode16, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174782117");
                    TemplateContext context16 = context5.subContext();
                    {
                      final SNode tnode17 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e96L, "jetbrains.mps.baseLanguage.structure.AssignmentExpression"));
                      try {
                        environment.nodeCopied(context16, tnode17, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174783163");
                        TemplateContext context17 = context16.subContext();
                        {
                          final SNode tnode18 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, "jetbrains.mps.baseLanguage.tuples.structure.IndexedTupleLiteral"));
                          try {
                            environment.nodeCopied(context17, tnode18, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174783691");
                            TemplateContext context18 = context17.subContext();
                            {
                              final SNode tnode19 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940cd6167L, "jetbrains.mps.baseLanguage.structure.NullLiteral"));
                              try {
                                environment.nodeCopied(context18, tnode19, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174784557");
                              } finally {
                              }
                              if (tnode19 != null) {
                                tnode18.addChild(MetaAdapterFactory.getContainmentLink(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, 0x1207171832eL, "component"), tnode19);
                              }
                              // TODO validate child 
                            }
                            {
                              final SNode tnode20 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940cd6167L, "jetbrains.mps.baseLanguage.structure.NullLiteral"));
                              try {
                                environment.nodeCopied(context18, tnode20, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174784623");
                              } finally {
                              }
                              if (tnode20 != null) {
                                tnode18.addChild(MetaAdapterFactory.getContainmentLink(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, 0x1207171832eL, "component"), tnode20);
                              }
                              // TODO validate child 
                            }
                          } finally {
                          }
                          if (tnode18 != null) {
                            tnode17.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue"), tnode18);
                          }
                          // TODO validate child 
                        }
                        {
                          final SNode tnode21 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, "jetbrains.mps.baseLanguage.tuples.structure.IndexedTupleLiteral"));
                          try {
                            environment.nodeCopied(context17, tnode21, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174782115");
                            TemplateContext context21 = context17.subContext();
                            {
                              final SNode tnode22 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                              try {
                                environment.nodeCopied(context21, tnode22, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174782986");
                                tnode22.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration"), tnode22, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("1672594678668584490")));
                              } finally {
                              }
                              if (tnode22 != null) {
                                tnode21.addChild(MetaAdapterFactory.getContainmentLink(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, 0x1207171832eL, "component"), tnode22);
                              }
                              // TODO validate child 
                            }
                            {
                              final SNode tnode23 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                              try {
                                environment.nodeCopied(context21, tnode23, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5841812207174783022");
                                tnode23.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration"), tnode23, PersistenceFacade.getInstance().createModelReference("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)"), PersistenceFacade.getInstance().createNodeId("6250046037307796326")));
                              } finally {
                              }
                              if (tnode23 != null) {
                                tnode21.addChild(MetaAdapterFactory.getContainmentLink(0xa247e09e243545baL, 0xb8d207e93feba96aL, 0x12071708c13L, 0x1207171832eL, "component"), tnode23);
                              }
                              // TODO validate child 
                            }
                          } finally {
                          }
                          if (tnode21 != null) {
                            tnode17.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue"), tnode21);
                          }
                          // TODO validate child 
                        }
                      } finally {
                      }
                      if (tnode17 != null) {
                        tnode16.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode17);
                      }
                      // TODO validate child 
                    }
                  } finally {
                  }
                  if (tnode16 != null) {
                    tlist15 = TemplateUtil.singletonList(tnode16);
                  }
                }
              }
            }
            for (SNode child24 : TemplateUtil.asNotNull(tlist15)) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child24);
            }
            // TODO validate child 
          }
          {
            final SNode tnode25 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b215L, "jetbrains.mps.baseLanguage.structure.Statement"));
            try {
              environment.nodeCopied(context5, tnode25, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940692068081");
            } finally {
            }
            if (tnode25 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode25);
            }
            // TODO validate child 
          }
          {
            final SNode tnode26 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
            try {
              environment.nodeCopied(context5, tnode26, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851699");
              TemplateContext context26 = context5.subContext();
              {
                final SNode tnode27 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                try {
                  environment.nodeCopied(context26, tnode27, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700");
                  SNodeAccessUtil.setProperty(tnode27, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "false");
                  SNodeAccessUtil.setProperty(tnode27, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "image");
                  TemplateContext context27 = context26.subContext();
                  {
                    final SNode tnode28 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                    try {
                      environment.nodeCopied(context27, tnode28, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5534405333772924270");
                      tnode28.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode28, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5534405333772914929")));
                    } finally {
                    }
                    if (tnode28 != null) {
                      tnode27.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode28);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode27 != null) {
                  tnode26.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode27);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode26 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode26);
            }
            // TODO validate child 
          }
          {
            final SNode tnode29 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, "jetbrains.mps.baseLanguage.structure.TryCatchStatement"));
            try {
              environment.nodeCopied(context5, tnode29, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954136974");
              TemplateContext context29 = context5.subContext();
              {
                final SNode tnode30 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
                try {
                  environment.nodeCopied(context29, tnode30, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954136976");
                  TemplateContext context30 = context29.subContext();
                  {
                    final SNode tnode31 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                    try {
                      environment.nodeCopied(context30, tnode31, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954141225");
                      TemplateContext context31 = context30.subContext();
                      {
                        final SNode tnode32 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e96L, "jetbrains.mps.baseLanguage.structure.AssignmentExpression"));
                        try {
                          environment.nodeCopied(context31, tnode32, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954141537");
                          TemplateContext context32 = context31.subContext();
                          {
                            final SNode tnode33 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, "jetbrains.mps.baseLanguage.structure.GenericNewExpression"));
                            try {
                              environment.nodeCopied(context32, tnode33, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954141605");
                              TemplateContext context33 = context32.subContext();
                              {
                                final SNode tnode34 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11a59b0fbceL, "jetbrains.mps.baseLanguage.structure.ClassCreator"));
                                try {
                                  environment.nodeCopied(context33, tnode34, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954155124");
                                  tnode34.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode34, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5534405333774307914")));
                                  TemplateContext context34 = context33.subContext();
                                  {
                                    final SNode tnode35 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                    try {
                                      environment.nodeCopied(context34, tnode35, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954155196");
                                      environment.resolveInTemplateLater(tnode35, "variableDeclaration", templateNode_2u1i0t_c0a1a1a3a1a2a1a2a1a2a1a2a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851684", "imagePath", context34);
                                    } finally {
                                    }
                                    if (tnode35 != null) {
                                      tnode34.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode35);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode34 != null) {
                                  tnode33.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator"), tnode34);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode33 != null) {
                              tnode32.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e99L, "rValue"), tnode33);
                            }
                            // TODO validate child 
                          }
                          {
                            final SNode tnode36 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                            try {
                              environment.nodeCopied(context32, tnode36, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954141223");
                              environment.resolveInTemplateLater(tnode36, "variableDeclaration", templateNode_2u1i0t_c0a1a1a3a1a2a1a2a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700", "image", context32);
                            } finally {
                            }
                            if (tnode36 != null) {
                              tnode32.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11b0d00332cL, 0xf8c77f1e97L, "lValue"), tnode36);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode32 != null) {
                          tnode31.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode32);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode31 != null) {
                      tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode31);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode37 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclarationStatement"));
                    try {
                      environment.nodeCopied(context30, tnode37, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851737");
                      TemplateContext context37 = context30.subContext();
                      {
                        final SNode tnode38 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                        try {
                          environment.nodeCopied(context37, tnode38, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851738");
                          SNodeAccessUtil.setProperty(tnode38, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "editorCell");
                          TemplateContext context38 = context37.subContext();
                          {
                            final SNode tnode39 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                            try {
                              environment.nodeCopied(context38, tnode39, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3288318341320741702");
                              tnode39.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode39, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("3288318341320524274")));
                            } finally {
                            }
                            if (tnode39 != null) {
                              tnode38.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode39);
                            }
                            // TODO validate child 
                          }
                          {
                            final SNode tnode40 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, "jetbrains.mps.baseLanguage.structure.StaticMethodCall"));
                            try {
                              environment.nodeCopied(context38, tnode40, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851740");
                              tnode40.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbbebabf09L, 0x10a7588b546L, "classConcept"), tnode40, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("3288318341320524274")));
                              tnode40.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode40, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("3288318341320526938")));
                              TemplateContext context40 = context38.subContext();
                              {
                                final SNode tnode41 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context40, tnode41, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851741");
                                  environment.resolveInTemplateLater(tnode41, "variableDeclaration", templateNode_2u1i0t_c0a1a1a4a1a4a1a2a1a3a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849742", "editorContext", context40);
                                } finally {
                                }
                                if (tnode41 != null) {
                                  tnode40.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode41);
                                }
                                // TODO validate child 
                              }
                              {
                                final SNode tnode42 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context40, tnode42, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851742");
                                  environment.resolveInTemplateLater(tnode42, "variableDeclaration", templateNode_2u1i0t_c0a1a1a5a1a4a1a2a1a3a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849744", "node", context40);
                                } finally {
                                }
                                if (tnode42 != null) {
                                  tnode40.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode42);
                                }
                                // TODO validate child 
                              }
                              {
                                final SNode tnode43 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context40, tnode43, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851743");
                                  environment.resolveInTemplateLater(tnode43, "variableDeclaration", templateNode_2u1i0t_c0a1a1a6a1a4a1a2a1a3a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700", "image", context40);
                                } finally {
                                }
                                if (tnode43 != null) {
                                  tnode40.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode43);
                                }
                                // TODO validate child 
                              }
                              {
                                final SNode tnode44 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context40, tnode44, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3288318341320836426");
                                  environment.resolveInTemplateLater(tnode44, "variableDeclaration", templateNode_2u1i0t_c0a1a1a7a1a4a1a2a1a3a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851684", "imagePath", context40);
                                } finally {
                                }
                                if (tnode44 != null) {
                                  tnode40.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode44);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode40 != null) {
                              tnode38.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer"), tnode40);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode38 != null) {
                          tnode37.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration"), tnode38);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode37 != null) {
                      tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode37);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode45 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, "jetbrains.mps.baseLanguage.structure.ExpressionStatement"));
                    try {
                      environment.nodeCopied(context30, tnode45, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5534405333775252452");
                      TemplateContext context45 = context30.subContext();
                      {
                        final SNode tnode46 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                        try {
                          environment.nodeCopied(context45, tnode46, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5534405333775252726");
                          TemplateContext context46 = context45.subContext();
                          {
                            final SNode tnode47 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                            try {
                              environment.nodeCopied(context46, tnode47, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5534405333775252450");
                              environment.resolveInTemplateLater(tnode47, "variableDeclaration", templateNode_2u1i0t_c0a1a1a2a1a2a1a4a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851700", "image", context46);
                            } finally {
                            }
                            if (tnode47 != null) {
                              tnode46.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode47);
                            }
                            // TODO validate child 
                          }
                          {
                            final SNode tnode48 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                            try {
                              environment.nodeCopied(context46, tnode48, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5534405333775253488");
                              tnode48.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode48, PersistenceFacade.getInstance().createModelReference("r:daca92ca-e9ce-48ae-833b-4f2157fecb32(org.campagnelab.editor.images.EditorCode)"), PersistenceFacade.getInstance().createNodeId("5534405333775179449")));
                              TemplateContext context48 = context46.subContext();
                              {
                                final SNode tnode49 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                try {
                                  environment.nodeCopied(context48, tnode49, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/5534405333775254183");
                                  environment.resolveInTemplateLater(tnode49, "variableDeclaration", templateNode_2u1i0t_c0a1a1a3a1a3a1a2a1a4a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851738", "editorCell", context48);
                                } finally {
                                }
                                if (tnode49 != null) {
                                  tnode48.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode49);
                                }
                                // TODO validate child 
                              }
                              {
                                final SNode tnode50 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                                try {
                                  environment.nodeCopied(context48, tnode50, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9084909247580244766");
                                  TemplateContext context50 = context48.subContext();
                                  {
                                    final SNode tnode51 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x10aaf6d7435L, "jetbrains.mps.lang.smodel.structure.SemanticDowncastExpression"));
                                    try {
                                      environment.nodeCopied(context50, tnode51, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9084909247580244646");
                                      TemplateContext context51 = context50.subContext();
                                      {
                                        final SNode tnode52 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, "jetbrains.mps.baseLanguage.structure.DotExpression"));
                                        try {
                                          environment.nodeCopied(context51, tnode52, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9084909247580244041");
                                          TemplateContext context52 = context51.subContext();
                                          {
                                            final SNode tnode53 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                                            try {
                                              environment.nodeCopied(context52, tnode53, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9084909247580243745");
                                              environment.resolveInTemplateLater(tnode53, "variableDeclaration", templateNode_2u1i0t_c0a1a1a2a1a2a1a2a1a4a1a3a1a2a1a4a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849744", "node", context52);
                                            } finally {
                                            }
                                            if (tnode53 != null) {
                                              tnode52.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode53);
                                            }
                                            // TODO validate child 
                                          }
                                          {
                                            final SNode tnode54 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x10a2e126334L, "jetbrains.mps.lang.smodel.structure.Node_GetModelOperation"));
                                            try {
                                              environment.nodeCopied(context52, tnode54, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9084909247580244314");
                                            } finally {
                                            }
                                            if (tnode54 != null) {
                                              tnode52.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode54);
                                            }
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        if (tnode52 != null) {
                                          tnode51.addChild(MetaAdapterFactory.getContainmentLink(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x10aaf6d7435L, 0x10aaf6f6e81L, "leftExpression"), tnode52);
                                        }
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    if (tnode51 != null) {
                                      tnode50.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand"), tnode51);
                                    }
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode55 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x118154a6332L, "jetbrains.mps.baseLanguage.structure.InstanceMethodCallOperation"));
                                    try {
                                      environment.nodeCopied(context50, tnode55, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/9084909247580245679");
                                      tnode55.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration"), tnode55, PersistenceFacade.getInstance().createModelReference("8865b7a8-5271-43d3-884c-6fd1d9cfdd34/java:org.jetbrains.mps.openapi.model(MPS.OpenAPI/)"), PersistenceFacade.getInstance().createNodeId("~SModel.getRepository():org.jetbrains.mps.openapi.module.SRepository")));
                                    } finally {
                                    }
                                    if (tnode55 != null) {
                                      tnode50.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode55);
                                    }
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                if (tnode50 != null) {
                                  tnode48.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument"), tnode50);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            if (tnode48 != null) {
                              tnode46.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation"), tnode48);
                            }
                            // TODO validate child 
                          }
                        } finally {
                        }
                        if (tnode46 != null) {
                          tnode45.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression"), tnode46);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode45 != null) {
                      tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode45);
                    }
                    // TODO validate child 
                  }
                  {
                    Collection<SNode> tlist56 = null;
                    try {
                      try {
                        tlist56 = environment.applyTemplate(new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "5170495790389304146"), new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851745"), context30);
                      } finally {
                      }

                    } finally {
                    }
                    for (SNode child57 : TemplateUtil.asNotNull(tlist56)) {
                      tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child57);
                    }
                    // TODO validate child 
                  }
                  {
                    Collection<SNode> tlist58 = null;
                    tlist58 = environment.applyTemplate(new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "6287772348368334582"), new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851749"), context30);
                    for (SNode child59 : TemplateUtil.asNotNull(tlist58)) {
                      tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), child59);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode60 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, "jetbrains.mps.baseLanguage.structure.ReturnStatement"));
                    try {
                      environment.nodeCopied(context30, tnode60, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954159760");
                      TemplateContext context60 = context30.subContext();
                      {
                        final SNode tnode61 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, "jetbrains.mps.baseLanguage.structure.VariableReference"));
                        try {
                          environment.nodeCopied(context60, tnode61, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954160380");
                          environment.resolveInTemplateLater(tnode61, "variableDeclaration", templateNode_2u1i0t_c0a1a1a2a1a7a1a2a1a8a1a5a3a2, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851738", "editorCell", context60);
                        } finally {
                        }
                        if (tnode61 != null) {
                          tnode60.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression"), tnode61);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode60 != null) {
                      tnode30.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode60);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode30 != null) {
                  tnode29.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, 0x10f383e83d4L, "body"), tnode30);
                }
                // TODO validate child 
              }
              {
                final SNode tnode62 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, "jetbrains.mps.baseLanguage.structure.CatchClause"));
                try {
                  environment.nodeCopied(context29, tnode62, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954136977");
                  TemplateContext context62 = context29.subContext();
                  {
                    final SNode tnode63 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7efL, "jetbrains.mps.baseLanguage.structure.LocalVariableDeclaration"));
                    try {
                      environment.nodeCopied(context62, tnode63, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954136979");
                      SNodeAccessUtil.setProperty(tnode63, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "npe");
                      TemplateContext context63 = context62.subContext();
                      {
                        final SNode tnode64 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
                        try {
                          environment.nodeCopied(context63, tnode64, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954137635");
                          tnode64.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode64, PersistenceFacade.getInstance().createModelReference("6354ebe7-c22a-4a0f-ac54-50b52ab9b065/java:java.lang(JDK/)"), PersistenceFacade.getInstance().createNodeId("~NullPointerException")));
                        } finally {
                        }
                        if (tnode64 != null) {
                          tnode63.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode64);
                        }
                        // TODO validate child 
                      }
                    } finally {
                    }
                    if (tnode63 != null) {
                      tnode62.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, 0x10f39a6a2f1L, "throwable"), tnode63);
                    }
                    // TODO validate child 
                  }
                  {
                    final SNode tnode65 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, "jetbrains.mps.baseLanguage.structure.StatementList"));
                    try {
                      environment.nodeCopied(context62, tnode65, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954136983");
                    } finally {
                    }
                    if (tnode65 != null) {
                      tnode62.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f39a56e2fL, 0x10f39a6a2f2L, "catchBody"), tnode65);
                    }
                    // TODO validate child 
                  }
                } finally {
                }
                if (tnode62 != null) {
                  tnode29.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10f383e6771L, 0x10f39a8ba1fL, "catchClause"), tnode62);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode29 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode29);
            }
            // TODO validate child 
          }
          {
            final SNode tnode66 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, "jetbrains.mps.baseLanguage.structure.ReturnStatement"));
            try {
              environment.nodeCopied(context5, tnode66, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688851754");
              TemplateContext context66 = context5.subContext();
              {
                final SNode tnode67 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf940cd6167L, "jetbrains.mps.baseLanguage.structure.NullLiteral"));
                try {
                  environment.nodeCopied(context66, tnode67, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3873701307954160884");
                } finally {
                }
                if (tnode67 != null) {
                  tnode66.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7feL, 0xf8cc6bf96cL, "expression"), tnode67);
                }
                // TODO validate child 
              }
            } finally {
            }
            if (tnode66 != null) {
              tnode5.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnode66);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode5 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1ffL, "body"), tnode5);
        }
        // TODO validate child 
      }
      {
        final SNode tnode68 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e94L, "jetbrains.mps.baseLanguage.structure.ParameterDeclaration"));
        try {
          environment.nodeCopied(context2, tnode68, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849742");
          SNodeAccessUtil.setProperty(tnode68, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "editorContext");
          SNodeAccessUtil.setProperty(tnode68, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "true");
          TemplateContext context68 = context2.subContext();
          {
            final SNode tnode69 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, "jetbrains.mps.baseLanguage.structure.ClassifierType"));
            try {
              environment.nodeCopied(context68, tnode69, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849743");
              tnode69.setReference(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), SReference.create(MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier"), tnode69, PersistenceFacade.getInstance().createModelReference("1ed103c3-3aa6-49b7-9c21-6765ee11f224/java:jetbrains.mps.openapi.editor(MPS.Editor/)"), PersistenceFacade.getInstance().createNodeId("~EditorContext")));
            } finally {
            }
            if (tnode69 != null) {
              tnode68.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode69);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode68 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1feL, "parameter"), tnode68);
        }
        // TODO validate child 
      }
      {
        final SNode tnode70 = environment.createOutputNode(MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e94L, "jetbrains.mps.baseLanguage.structure.ParameterDeclaration"));
        try {
          environment.nodeCopied(context2, tnode70, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849744");
          SNodeAccessUtil.setProperty(tnode70, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "node");
          SNodeAccessUtil.setProperty(tnode70, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0x111f9e9f00cL, "isFinal"), "true");
          TemplateContext context70 = context2.subContext();
          {
            final SNode tnode71 = environment.createOutputNode(MetaAdapterFactory.getConcept(0x7866978ea0f04cc7L, 0x81bc4d213d9375e1L, 0x108f968b3caL, "jetbrains.mps.lang.smodel.structure.SNodeType"));
            try {
              environment.nodeCopied(context70, tnode71, "tpl/r:4d30284c-d4f6-4b68-8efd-29ee046f3381/3219955940688849745");
            } finally {
            }
            if (tnode71 != null) {
              tnode70.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type"), tnode71);
            }
            // TODO validate child 
          }
        } finally {
        }
        if (tnode70 != null) {
          tnode2.addChild(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b1fcL, 0xf8cc56b1feL, "parameter"), tnode70);
        }
        // TODO validate child 
      }
    } finally {
    }
    environment.registerLabel(context.getInput(), tnode2, "cellFactoryMethod");
    return tnode2;
  }
  @Override
  public Collection<SNode> apply(@NotNull TemplateExecutionEnvironment environment, @NotNull TemplateContext context) throws GenerationException {
    return TemplateUtil.singletonList(applyPart0(context));
  }

  @Override
  public Collection<SNode> weave(@NotNull NodeWeaveFacility.WeaveContext weaveContext, @NotNull NodeWeaveFacility weaveSupport) throws GenerationException {
    final TemplateContext templateContext = weaveSupport.getTemplateContext();
    SNode tnodepart0 = applyPart0(templateContext);
    weaveSupport.weaveNode(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101d9d3ca30L, 0x4a9a46de59132803L, "member"), tnodepart0);
    return TemplateUtil.singletonList(tnodepart0);
  }
  private static SNodePointer propertyMacro_2u1i0t_c0a0c0b0d0c = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688849734");
  private static SNodePointer switchMacroRef_2u1i0t_b0a0a0a1a5a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5841812207174784809");
  private static SNodePointer templateSwitchNode_2u1i0t_a0a0c0a1a1a5a1a5a3a2 = new SNodePointer("r:00000000-0000-4000-0000-011c8959029f(jetbrains.mps.lang.editor.generator.baseLanguage.template.main@generator)", "5841812207174733785");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a3a1a2a1a2a1a2a1a2a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3873701307954155196");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a3a1a2a1a2a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3873701307954141223");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a4a1a4a1a2a1a3a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851741");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a5a1a4a1a2a1a3a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851742");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a6a1a4a1a2a1a3a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3219955940688851743");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a7a1a4a1a2a1a3a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3288318341320836426");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a2a1a2a1a4a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5534405333775252450");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a3a1a3a1a2a1a4a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "5534405333775254183");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a2a1a2a1a2a1a4a1a3a1a2a1a4a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "9084909247580243745");
  private static SNodePointer templateNode_2u1i0t_c0a1a1a2a1a7a1a2a1a8a1a5a3a2 = new SNodePointer("r:4d30284c-d4f6-4b68-8efd-29ee046f3381(org.campagnelab.editor.images.generator.template.main@generator)", "3873701307954160380");
}
