package org.campagnelab.hta.script.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class Statement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Statement_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_dependencies_7074867102588635969(SNode thisNode) {
    return Statement_Behavior.virtual_dependencies_7074867102588635969(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.hta.script.structure.Statement";
  }
}
