package org.campagnelab.metar.tables.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;

public class DeleteColumnGroup {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new DeleteColumnGroup.DeleteColumnGroup_DELETE(node));
    editorCell.setAction(CellActionType.BACKSPACE, new DeleteColumnGroup.DeleteColumnGroup_BACKSPACE(node));
  }

  public static class DeleteColumnGroup_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;

    public DeleteColumnGroup_DELETE(SNode node) {
      this.myNode = node;
    }

    public String getDescriptionText() {
      return "Delete Column Group";
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      AttributeOperations.setAttribute(SNodeOperations.getAncestor(node, "org.campagnelab.mps.XChart.structure.Column", true, false), new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation"), null);
    }
  }

  public static class DeleteColumnGroup_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;

    public DeleteColumnGroup_BACKSPACE(SNode node) {
      this.myNode = node;
    }

    public String getDescriptionText() {
      return "Delete Column Group";
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      AttributeOperations.setAttribute(SNodeOperations.getAncestor(node, "org.campagnelab.mps.XChart.structure.Column", true, false), new IAttributeDescriptor.NodeAttribute("org.campagnelab.metar.tables.structure.ColumnAnnotation"), null);
    }
  }
}
