package org.campagnelab.hta.script.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.DependentOnPackage").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").references("package").create();
      case 1:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.EmptyLine").super_("org.campagnelab.hta.script.structure.Statement").parents("org.campagnelab.hta.script.structure.Statement").alias("<empty line> ", "").create();
      case 2:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.R_Package").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").alias("R Package", "Models an R package").create();
      case 3:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.Script").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.lang.core.structure.ScopeProvider").children(new String[]{"statements"}, new boolean[]{false}).alias("script", "").create();
      case 4:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.Statement").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "org.campagnelab.hta.script.structure.StatementDependencies").properties("id").abstract_().create();
      case 5:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.StatementDependencies").interface_().create();
      case 6:
        return new ConceptDescriptorBuilder("org.campagnelab.hta.script.structure.StatementList").super_("org.campagnelab.hta.script.structure.Statement").parents("org.campagnelab.hta.script.structure.Statement", "jetbrains.mps.lang.core.structure.ScopeProvider").children(new String[]{"transformations"}, new boolean[]{true}).create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"org.campagnelab.hta.script.structure.DependentOnPackage", "org.campagnelab.hta.script.structure.EmptyLine", "org.campagnelab.hta.script.structure.R_Package", "org.campagnelab.hta.script.structure.Script", "org.campagnelab.hta.script.structure.Statement", "org.campagnelab.hta.script.structure.StatementDependencies", "org.campagnelab.hta.script.structure.StatementList"};
}
