package org.campagnelab.metar.functions.access.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import org.campagnelab.metar.code.generator.helpers.NameHelper;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;
  public static Object propertyMacro_GetPropertyValue_5870486266827288475(final PropertyMacroContext _context) {
    String tableName = NameHelper.RName(SPropertyOperations.getString(SNodeOperations.getNodeAncestor(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x64c9046609b241abL, 0x89f85085b3b9eca7L, 0x5178282811051f99L, 0x5178282811051f9aL, "column")), MetaAdapterFactory.getConcept(0x5d6bde844ce44eb5L, 0xa37e25a5edd55129L, 0x2f3745fadd522533L, "org.campagnelab.metar.tables.structure.Table"), false, false), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    return tableName + "$\"" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x64c9046609b241abL, 0x89f85085b3b9eca7L, 0x5178282811051f99L, 0x5178282811051f9aL, "column")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "\"";
  }
  public static SNode sourceNodeQuery_1669016037359836706(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x64c9046609b241abL, 0x89f85085b3b9eca7L, 0xfa69225966133a1L, 0xfa69225966133a2L, "call")), MetaAdapterFactory.getContainmentLink(0x64c9046609b241abL, 0x89f85085b3b9eca7L, 0xfa69225978829dcL, 0xfa69225978829ddL, "call"));
  }
  public static SNode sourceNodeQuery_7174230558147545331(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x64c9046609b241abL, 0x89f85085b3b9eca7L, 0xfa69225978829dcL, 0xfa69225978829ddL, "call"));
  }
}
