package org.campagnelab.metar.tables.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class JoinTables_Constraints extends BaseConstraintsDescriptor {
  public JoinTables_Constraints() {
    super("org.campagnelab.metar.tables.structure.JoinTables");
  }
}
